"""2fa, bloqueio de conta e tempo de prova

Revision ID: 3fd207b0885f
Revises: 40992fa1d33a
Create Date: 2026-06-17 15:10:46.004469

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3fd207b0885f'
down_revision = '40992fa1d33a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tempo_limite_min', sa.Integer(), nullable=True))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=64), nullable=True))
        # sa.false(): booleano portável (DEFAULT 0 é rejeitado pelo PostgreSQL).
        batch_op.add_column(sa.Column('mfa_ativo', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('tentativas_falhas', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('bloqueado_ate', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('bloqueado_ate')
        batch_op.drop_column('tentativas_falhas')
        batch_op.drop_column('mfa_ativo')
        batch_op.drop_column('totp_secret')

    with op.batch_alter_table('provas', schema=None) as batch_op:
        batch_op.drop_column('tempo_limite_min')

    # ### end Alembic commands ###
