"""diagnostico de maturidade e auditoria

Revision ID: 40992fa1d33a
Revises: 9d4da826ffc0
Create Date: 2026-06-17 14:21:16.927086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40992fa1d33a'
down_revision = '9d4da826ffc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostico_perguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dimensao', sa.String(length=20), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnostico_perguntas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnostico_perguntas_dimensao'), ['dimensao'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=120), nullable=False),
    sa.Column('detalhe', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('diagnosticos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('finalizado_em', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('nivel', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnosticos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnosticos_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosticos_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('diagnostico_respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagnostico_id', sa.Integer(), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diagnostico_id'], ['diagnosticos.id'], ),
    sa.ForeignKeyConstraint(['pergunta_id'], ['diagnostico_perguntas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnostico_respostas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnostico_respostas_diagnostico_id'), ['diagnostico_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostico_respostas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnostico_respostas_diagnostico_id'))

    op.drop_table('diagnostico_respostas')
    with op.batch_alter_table('diagnosticos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnosticos_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_diagnosticos_empresa_id'))

    op.drop_table('diagnosticos')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_criado_em'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('diagnostico_perguntas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnostico_perguntas_dimensao'))

    op.drop_table('diagnostico_perguntas')
    # ### end Alembic commands ###
