"""ropa e pedidos do titular

Revision ID: 7a06145bac02
Revises: afce8b02a0a7
Create Date: 2026-06-17 21:43:24.637412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a06145bac02'
down_revision = 'afce8b02a0a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ropa_registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.Column('atividade', sa.String(length=200), nullable=False),
    sa.Column('titulares', sa.String(length=255), nullable=True),
    sa.Column('categorias_dados', sa.Text(), nullable=True),
    sa.Column('finalidade', sa.Text(), nullable=True),
    sa.Column('base_legal', sa.String(length=40), nullable=True),
    sa.Column('retencao', sa.String(length=255), nullable=True),
    sa.Column('compartilhamento', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ropa_registros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ropa_registros_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ropa_registros_setor_id'), ['setor_id'], unique=False)

    op.create_table('pedidos_titular',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome_titular', sa.String(length=160), nullable=False),
    sa.Column('contato', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('prazo', sa.DateTime(), nullable=True),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedidos_titular', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_titular_empresa_id'), ['empresa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos_titular', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_titular_empresa_id'))

    op.drop_table('pedidos_titular')
    with op.batch_alter_table('ropa_registros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ropa_registros_setor_id'))
        batch_op.drop_index(batch_op.f('ix_ropa_registros_empresa_id'))

    op.drop_table('ropa_registros')
    # ### end Alembic commands ###
