"""esquema inicial

Revision ID: 9d4da826ffc0
Revises: 
Create Date: 2026-06-17 11:23:55.084417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d4da826ffc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresas_slug'), ['slug'], unique=True)

    op.create_table('questoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(length=20), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('artigo', sa.String(length=120), nullable=True),
    sa.Column('explicacao', sa.Text(), nullable=True),
    sa.Column('dificuldade', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questoes_area'), ['area'], unique=False)
        batch_op.create_index(batch_op.f('ix_questoes_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('setores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('area', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'slug', name='uq_setor_empresa_slug')
    )
    with op.batch_alter_table('setores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setores_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('trilhas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('resumo', sa.String(length=300), nullable=True),
    sa.Column('conteudo_md', sa.Text(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('publicada', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trilhas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trilhas_area'), ['area'], unique=False)
        batch_op.create_index(batch_op.f('ix_trilhas_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trilhas_slug'), ['slug'], unique=False)

    op.create_table('alternativas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=500), nullable=False),
    sa.Column('correta', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alternativas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alternativas_questao_id'), ['questao_id'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_setor_id'), ['setor_id'], unique=False)

    op.create_table('provas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(length=20), nullable=False),
    sa.Column('nota_corte', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.Column('aprovado', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('finalizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provas_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provas_setor_id'), ['setor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provas_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('certificados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('prova_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(length=20), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nota', sa.Float(), nullable=False),
    sa.Column('emitido_em', sa.DateTime(), nullable=False),
    sa.Column('valido_ate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['prova_id'], ['provas.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificados_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_certificados_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificados_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('prova_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prova_id', sa.Integer(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ordem_alternativas', sa.String(length=120), nullable=True),
    sa.Column('alternativa_escolhida_id', sa.Integer(), nullable=True),
    sa.Column('correta', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['alternativa_escolhida_id'], ['alternativas.id'], ),
    sa.ForeignKeyConstraint(['prova_id'], ['provas.id'], ),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prova_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prova_itens_prova_id'), ['prova_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prova_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prova_itens_prova_id'))

    op.drop_table('prova_itens')
    with op.batch_alter_table('certificados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificados_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_certificados_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_certificados_codigo'))

    op.drop_table('certificados')
    with op.batch_alter_table('provas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provas_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_provas_setor_id'))
        batch_op.drop_index(batch_op.f('ix_provas_empresa_id'))

    op.drop_table('provas')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_setor_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('alternativas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alternativas_questao_id'))

    op.drop_table('alternativas')
    with op.batch_alter_table('trilhas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trilhas_slug'))
        batch_op.drop_index(batch_op.f('ix_trilhas_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_trilhas_area'))

    op.drop_table('trilhas')
    with op.batch_alter_table('setores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setores_empresa_id'))

    op.drop_table('setores')
    with op.batch_alter_table('questoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questoes_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_questoes_area'))

    op.drop_table('questoes')
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresas_slug'))

    op.drop_table('empresas')
    # ### end Alembic commands ###
