"""2fa obrigatorio, recovery codes e diagnostico por setor

Revision ID: afce8b02a0a7
Revises: 3fd207b0885f
Create Date: 2026-06-17 18:53:48.406675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afce8b02a0a7'
down_revision = '3fd207b0885f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('usado', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_codes_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('diagnosticos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setor_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_diagnosticos_setor_id'), ['setor_id'], unique=False)
        batch_op.create_foreign_key('fk_diagnosticos_setor', 'setores', ['setor_id'], ['id'])

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_obrigatorio', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_column('mfa_obrigatorio')

    with op.batch_alter_table('diagnosticos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_diagnosticos_setor', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_diagnosticos_setor_id'))
        batch_op.drop_column('setor_id')

    with op.batch_alter_table('recovery_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_codes_usuario_id'))

    op.drop_table('recovery_codes')
    # ### end Alembic commands ###
