"""ripd e incidentes

Revision ID: eaedbce82aff
Revises: 7a06145bac02
Create Date: 2026-06-17 21:55:44.633681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaedbce82aff'
down_revision = '7a06145bac02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('ocorrido_em', sa.DateTime(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('dados_afetados', sa.Text(), nullable=True),
    sa.Column('num_titulares', sa.Integer(), nullable=True),
    sa.Column('risco', sa.String(length=20), nullable=True),
    sa.Column('comunicado_anpd', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('comunicado_anpd_em', sa.DateTime(), nullable=True),
    sa.Column('comunicado_titulares', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('comunicado_titulares_em', sa.DateTime(), nullable=True),
    sa.Column('medidas', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidentes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidentes_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('ripd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('ropa_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao_tratamento', sa.Text(), nullable=True),
    sa.Column('probabilidade', sa.Integer(), nullable=False),
    sa.Column('impacto', sa.Integer(), nullable=False),
    sa.Column('medidas', sa.Text(), nullable=True),
    sa.Column('risco_residual', sa.String(length=20), nullable=True),
    sa.Column('conclusao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['ropa_id'], ['ropa_registros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ripd', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ripd_empresa_id'), ['empresa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ripd', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ripd_empresa_id'))

    op.drop_table('ripd')
    with op.batch_alter_table('incidentes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidentes_empresa_id'))

    op.drop_table('incidentes')
    # ### end Alembic commands ###
