"""Banco de questões — parte A: GERAL, RH e FINANCEIRO.

Fontes: Lei nº 13.709/2018 (texto compilado, Planalto); Resoluções CD/ANPD nº 2/2022,
4/2023, 15/2024, 18/2024 e 19/2024; Enunciado CD/ANPD nº 1/2023; Guias Orientativos da
ANPD (Agentes de Tratamento e Encarregado v2.0/2022; Atuação do Encarregado 2024;
Legítimo Interesse 2024; Cookies 2022; Segurança da Informação para pequeno porte 2021).
"""

QUESTOES_A = {
    # ───────────────────────────── GERAL (toda a empresa) ─────────────────────────────
    "GERAL": [
        ("Segundo a LGPD, o que é dado pessoal?", "Art. 5º, I",
         "Dado pessoal é a informação relacionada a pessoa natural identificada ou identificável (Art. 5º, I).", 1,
         [("Informação relacionada a pessoa natural identificada ou identificável", True),
          ("Apenas CPF, RG e passaporte", False),
          ("Somente dados financeiros e bancários", False),
          ("Qualquer dado cadastral de uma empresa", False)]),
        ("Qual destes é dado pessoal sensível, na lista do Art. 5º, II?", "Art. 5º, II",
         "A lista do Art. 5º, II, inclui origem racial ou étnica, convicção religiosa, opinião política, filiação a "
         "sindicato, dado referente à saúde ou à vida sexual, dado genético ou biométrico. Telefone e endereço não estão nela.", 1,
         [("Filiação a sindicato", True), ("Número de telefone", False),
          ("Endereço residencial", False), ("Data de nascimento", False)]),
        ("Uma empresa (pessoa jurídica) pode ser 'titular' de dados na LGPD?", "Art. 5º, I e V",
         "Não. Titular é a pessoa natural a quem se referem os dados (Art. 5º, V); dado pessoal é informação "
         "relacionada a pessoa natural (Art. 5º, I). Os dados dos sócios e representantes, esses sim, são pessoais.", 2,
         [("Não: titular é sempre pessoa natural", True), ("Sim, qualquer pessoa jurídica é titular", False),
          ("Sim, desde que seja microempresa", False), ("Apenas empresas públicas", False)]),
        ("Quem toma as decisões referentes ao tratamento de dados pessoais é o:", "Art. 5º, VI",
         "Controlador: pessoa natural ou jurídica a quem competem as decisões referentes ao tratamento (Art. 5º, VI).", 1,
         [("Controlador", True), ("Operador", False), ("Titular", False), ("Encarregado", False)]),
        ("Quem realiza o tratamento de dados pessoais em nome do controlador é o:", "Art. 5º, VII",
         "Operador: pessoa natural ou jurídica que realiza o tratamento em nome do controlador (Art. 5º, VII).", 1,
         [("Operador", True), ("Controlador", False), ("Titular", False), ("Autoridade nacional", False)]),
        ("O encarregado (DPO) atua como canal de comunicação entre:", "Art. 5º, VIII",
         "O encarregado é a pessoa indicada para atuar como canal de comunicação entre o controlador, os titulares "
         "dos dados e a ANPD (Art. 5º, VIII).", 1,
         [("O controlador, os titulares e a ANPD", True), ("Apenas a empresa e o Procon", False),
          ("O operador e os fornecedores", False), ("A empresa e a Receita Federal", False)]),
        ("Qual destas operações é considerada 'tratamento' de dados pessoais?", "Art. 5º, X",
         "Tratamento é toda operação com dados pessoais: coleta, acesso, armazenamento, transmissão, eliminação, "
         "entre outras (Art. 5º, X). Até apagar dados é tratamento.", 1,
         [("Todas: coletar, armazenar, transmitir e eliminar", True), ("Apenas coletar", False),
          ("Apenas vender dados", False), ("Somente publicar na internet", False)]),
        ("Dados anonimizados são considerados dados pessoais para a LGPD?", "Art. 12",
         "Não, salvo quando a anonimização for revertida com meios próprios ou puder ser revertida com esforços "
         "razoáveis (Art. 12). Dados usados para perfil comportamental de pessoa identificada podem ser pessoais (§ 2º).", 2,
         [("Não, salvo se a anonimização puder ser revertida com esforços razoáveis", True),
          ("Sim, sempre", False), ("Nunca, em nenhuma hipótese", False), ("Só se forem dados sensíveis", False)]),
        ("Para ser válido, o consentimento deve ser uma manifestação:", "Art. 5º, XII",
         "Consentimento é manifestação livre, informada e inequívoca pela qual o titular concorda com o tratamento "
         "para uma finalidade determinada (Art. 5º, XII).", 1,
         [("Livre, informada e inequívoca, para finalidade determinada", True),
          ("Presumida pelo silêncio do titular", False), ("Genérica, valendo para qualquer finalidade", False),
          ("Verbal e sem possibilidade de revogação", False)]),
        ("Limitar o tratamento ao mínimo necessário para a finalidade é o princípio da:", "Art. 6º, III",
         "Necessidade: limitação do tratamento ao mínimo necessário, com dados pertinentes, proporcionais e não "
         "excessivos em relação às finalidades (Art. 6º, III).", 2,
         [("Necessidade", True), ("Livre acesso", False), ("Qualidade dos dados", False), ("Prevenção", False)]),
        ("Tratar dados para propósitos legítimos, específicos, explícitos e informados ao titular é o princípio da:",
         "Art. 6º, I",
         "Finalidade (Art. 6º, I), sem possibilidade de tratamento posterior de forma incompatível com esses propósitos.", 2,
         [("Finalidade", True), ("Segurança", False), ("Não discriminação", False), ("Transparência", False)]),
        ("Demonstrar a adoção de medidas eficazes e capazes de comprovar o cumprimento da lei é o princípio da:",
         "Art. 6º, X",
         "Responsabilização e prestação de contas (accountability): demonstração, pelo agente, da adoção de medidas "
         "eficazes e da sua eficácia (Art. 6º, X).", 2,
         [("Responsabilização e prestação de contas", True), ("Adequação", False),
          ("Livre acesso", False), ("Qualidade dos dados", False)]),
        ("Quantos princípios expressos o Art. 6º da LGPD lista (além da boa-fé do caput)?", "Art. 6º",
         "Dez: finalidade, adequação, necessidade, livre acesso, qualidade dos dados, transparência, segurança, "
         "prevenção, não discriminação e responsabilização e prestação de contas (Art. 6º, I a X).", 2,
         [("Dez", True), ("Cinco", False), ("Sete", False), ("Quinze", False)]),
        ("O consentimento é a única hipótese legal para tratar dados pessoais?", "Art. 7º",
         "Não. O Art. 7º lista dez hipóteses (I a X): consentimento, obrigação legal, políticas públicas, pesquisa, "
         "execução de contrato, exercício de direitos, proteção da vida, tutela da saúde, legítimo interesse e "
         "proteção do crédito.", 1,
         [("Não: o Art. 7º prevê dez hipóteses legais", True), ("Sim, é a única", False),
          ("Sim, exceto para órgãos públicos", False), ("Sim, para dados de clientes", False)]),
        ("Tratar dados para cumprir uma exigência da lei ou de um regulador tem como base legal:", "Art. 7º, II",
         "Cumprimento de obrigação legal ou regulatória pelo controlador (Art. 7º, II).", 2,
         [("Cumprimento de obrigação legal ou regulatória", True), ("Consentimento do titular", False),
          ("Legítimo interesse", False), ("Proteção ao crédito", False)]),
        ("A base legal de 'execução de contrato' exige que o tratamento seja necessário ao contrato e ocorra:",
         "Art. 7º, V",
         "A pedido do titular dos dados: tratamento necessário para a execução de contrato ou de procedimentos "
         "preliminares do qual o titular seja parte (Art. 7º, V).", 2,
         [("A pedido do titular, que é parte do contrato", True), ("Por decisão exclusiva da empresa", False),
          ("Com autorização da ANPD", False), ("Somente após consentimento por escrito", False)]),
        ("O legítimo interesse só pode fundamentar tratamento para finalidades legítimas consideradas a partir de:",
         "Art. 7º, IX e Art. 10",
         "Situações concretas (Art. 10, caput). O Guia da ANPD (2024) afasta interesses baseados em situações "
         "abstratas ou meramente especulativas e recomenda o teste de balanceamento antes do tratamento.", 3,
         [("Situações concretas, com teste de balanceamento", True), ("Qualquer vantagem comercial", False),
          ("Situações hipotéticas futuras", False), ("A vontade do gestor da área", False)]),
        ("Se a lei dispensa o consentimento em determinado caso, o controlador fica livre das demais obrigações da LGPD?",
         "Art. 7º, § 6º",
         "Não. A dispensa do consentimento não desobriga os agentes das demais obrigações, especialmente dos princípios "
         "e dos direitos do titular (Art. 7º, § 6º).", 3,
         [("Não: princípios e direitos do titular continuam valendo", True), ("Sim, integralmente", False),
          ("Sim, exceto quanto à segurança", False), ("Sim, para dados não sensíveis", False)]),
        ("Autorizações genéricas para o tratamento de dados pessoais são:", "Art. 8º, § 4º",
         "Nulas. O consentimento deve referir-se a finalidades determinadas (Art. 8º, § 4º).", 2,
         [("Nulas", True), ("Válidas por 12 meses", False), ("Válidas se assinadas", False),
          ("Válidas para dados não sensíveis", False)]),
        ("A quem cabe o ônus de provar que o consentimento foi obtido conforme a lei?", "Art. 8º, § 2º",
         "Ao controlador (Art. 8º, § 2º). Por isso o consentimento por escrito deve constar de cláusula destacada (§ 1º).", 3,
         [("Ao controlador", True), ("Ao titular", False), ("À ANPD", False), ("Ao operador", False)]),
        ("O titular pode revogar o consentimento:", "Art. 8º, § 5º",
         "A qualquer momento, mediante manifestação expressa, por procedimento gratuito e facilitado (Art. 8º, § 5º).", 2,
         [("A qualquer momento, por procedimento gratuito e facilitado", True),
          ("Somente após 12 meses", False), ("Apenas mediante pagamento de taxa", False),
          ("Nunca, depois de concedido", False)]),
        ("O legítimo interesse pode ser usado como base legal para dados pessoais sensíveis?", "Art. 11",
         "Não. O Art. 11 não prevê legítimo interesse entre as hipóteses para dados sensíveis; a hipótese do "
         "Art. 7º, IX, só se aplica a dados não sensíveis (Guia de Legítimo Interesse da ANPD, 2024).", 3,
         [("Não: o Art. 11 não prevê essa hipótese para dados sensíveis", True),
          ("Sim, sempre", False), ("Sim, com teste de balanceamento", False), ("Sim, para dados de saúde", False)]),
        ("Qual destes é um direito do titular previsto no Art. 18?", "Art. 18, V",
         "Portabilidade dos dados a outro fornecedor, mediante requisição expressa (Art. 18, V). Os demais itens não "
         "constam da lei.", 1,
         [("Portabilidade dos dados a outro fornecedor", True), ("Receber pagamento pelo uso dos dados", False),
          ("Acessar os dados de outros titulares", False), ("Exigir a demissão de quem tratou os dados", False)]),
        ("Prazo para o controlador fornecer a declaração clara e completa sobre a existência de tratamento e o acesso:",
         "Art. 19, II",
         "Até 15 (quinze) dias, contados do requerimento do titular (Art. 19, II). Em formato simplificado, "
         "a resposta é imediata (Art. 19, I).", 2,
         [("Até 15 dias", True), ("Até 72 horas", False), ("Até 30 dias", False), ("Até 90 dias", False)]),
        ("O atendimento aos requerimentos do titular (Art. 18) pode ser cobrado?", "Art. 18, § 5º",
         "Não: será atendido sem custos para o titular, nos prazos e termos previstos em regulamento (Art. 18, § 5º).", 2,
         [("Não, é sem custos para o titular", True), ("Sim, uma taxa administrativa", False),
          ("Sim, se o pedido for por escrito", False), ("Sim, para portabilidade", False)]),
        ("Diante de decisão tomada unicamente com base em tratamento automatizado, o titular tem direito a:",
         "Art. 20",
         "Solicitar a revisão da decisão, inclusive as que definem perfil pessoal, profissional, de consumo e de "
         "crédito (Art. 20). O controlador deve informar os critérios, observados os segredos comercial e industrial (§ 1º).", 2,
         [("Solicitar a revisão da decisão", True), ("Exigir indenização automática", False),
          ("Proibir o uso de computadores", False), ("Nada; decisões automatizadas são definitivas", False)]),
        ("Após o término do tratamento, os dados pessoais devem ser eliminados, salvo conservação para:",
         "Art. 16",
         "Cumprimento de obrigação legal ou regulatória; estudo por órgão de pesquisa; transferência a terceiro "
         "respeitada a lei; ou uso exclusivo do controlador, desde que anonimizados (Art. 16, I a IV).", 2,
         [("Obrigação legal, pesquisa, transferência lícita ou uso exclusivo anonimizado", True),
          ("Qualquer finalidade futura que a empresa imagine", False),
          ("Venda a parceiros comerciais", False), ("Nenhuma hipótese: sempre eliminar", False)]),
        ("O registro das operações de tratamento (ROPA) é obrigatório para:", "Art. 37",
         "Controlador E operador: ambos devem manter registro das operações que realizarem, especialmente quando "
         "baseadas no legítimo interesse (Art. 37).", 2,
         [("O controlador e o operador", True), ("Somente o controlador", False),
          ("Somente o operador", False), ("Apenas órgãos públicos", False)]),
        ("O relatório de impacto (RIPD) deve conter, no mínimo:", "Art. 38, parágrafo único",
         "A descrição dos tipos de dados coletados, a metodologia de coleta e de garantia da segurança e a análise "
         "das medidas, salvaguardas e mecanismos de mitigação de risco adotados (Art. 38, parágrafo único).", 3,
         [("Tipos de dados, metodologia de coleta e segurança, e medidas de mitigação de risco", True),
          ("Apenas a lista de funcionários", False), ("O faturamento da empresa", False),
          ("A senha dos sistemas", False)]),
        ("A identidade e o contato do encarregado devem ser:", "Art. 41, § 1º",
         "Divulgados publicamente, de forma clara e objetiva, preferencialmente no sítio eletrônico do controlador "
         "(Art. 41, § 1º). A Resolução CD/ANPD nº 18/2024 exige o nome completo, não apenas um e-mail.", 2,
         [("Divulgados publicamente, preferencialmente no site", True), ("Mantidos em sigilo", False),
          ("Informados apenas à ANPD", False), ("Divulgados só a pedido judicial", False)]),
        ("Orientar os funcionários e contratados sobre as práticas de proteção de dados é atribuição do:",
         "Art. 41, § 2º, III",
         "Do encarregado, entre suas atividades legais (Art. 41, § 2º, III), ao lado de receber comunicações dos "
         "titulares e da ANPD e adotar providências.", 1,
         [("Encarregado", True), ("Titular", False), ("Operador", False), ("Sindicato", False)]),
        ("O operador responde solidariamente pelos danos quando:", "Art. 42, § 1º, I",
         "Descumprir as obrigações da legislação de proteção de dados ou não seguir as instruções lícitas do "
         "controlador, hipótese em que se equipara ao controlador (Art. 42, § 1º, I).", 3,
         [("Descumpre a lei ou as instruções lícitas do controlador", True), ("Sempre, em qualquer caso", False),
          ("Nunca; a responsabilidade é só do controlador", False), ("Apenas se for empresa pública", False)]),
        ("As medidas de segurança do Art. 46 devem ser observadas:", "Art. 46, § 2º",
         "Desde a fase de concepção do produto ou do serviço até a sua execução (Art. 46, § 2º).", 2,
         [("Desde a concepção do produto ou serviço até a execução", True),
          ("Somente após o lançamento", False), ("Apenas quando a ANPD exigir", False),
          ("Só para sistemas com dados sensíveis", False)]),
        ("Quem deve comunicar um incidente de segurança com risco relevante, e a quem?", "Art. 48",
         "O controlador, à autoridade nacional E ao titular (Art. 48, caput). A ANPD esclarece que comunicar só à "
         "ANPD não cumpre a obrigação; havendo risco relevante, os titulares devem ser comunicados.", 2,
         [("O controlador, à ANPD e aos titulares", True), ("O operador, apenas à ANPD", False),
          ("O encarregado, apenas à polícia", False), ("Ninguém, se o incidente foi interno", False)]),
        ("Prazo para o controlador comunicar à ANPD um incidente que possa acarretar risco ou dano relevante:",
         "Art. 48 + Resolução CD/ANPD nº 15/2024, art. 6º",
         "Três dias úteis, contados do conhecimento pelo controlador de que o incidente afetou dados pessoais "
         "(Res. CD/ANPD nº 15/2024, art. 6º, § 1º). As 72 horas são regra do GDPR europeu, não da LGPD.", 2,
         [("3 dias úteis, contados do conhecimento de que afetou dados pessoais", True),
          ("72 horas", False), ("30 dias corridos", False), ("Não há prazo definido", False)]),
        ("Agentes de tratamento de pequeno porte, pela Resolução CD/ANPD nº 2/2022:", "Res. CD/ANPD nº 2/2022, arts. 11 e 14",
         "Não são obrigados a indicar encarregado, mas devem manter canal de comunicação com o titular (art. 11), e "
         "têm prazos em dobro para atender titulares e comunicar incidentes (art. 14).", 3,
         [("Dispensados do encarregado (com canal ao titular) e com prazos em dobro", True),
          ("Totalmente isentos da LGPD", False), ("Obrigados a ter encarregado certificado", False),
          ("Sujeitos a multa em dobro", False)]),
        ("A multa simples prevista na LGPD pode chegar a:", "Art. 52, II",
         "Até 2% do faturamento da pessoa jurídica, grupo ou conglomerado no Brasil no último exercício, excluídos os "
         "tributos, limitada, no total, a R$ 50.000.000,00 por infração (Art. 52, II).", 1,
         [("2% do faturamento, limitada a R$ 50 milhões por infração", True),
          ("10% do faturamento, sem limite", False), ("R$ 1.000 por dia, sem teto", False),
          ("Prisão do administrador", False)]),
        ("Órgãos e entidades públicos podem receber multa da ANPD?", "Art. 52, § 3º",
         "Não. A eles aplicam-se apenas advertência e as sanções não pecuniárias (incisos I, IV, V, VI, X, XI e XII), "
         "conforme Art. 52, § 3º, e Res. CD/ANPD nº 4/2023, art. 3º, § 5º.", 3,
         [("Não: só advertência e sanções não pecuniárias", True), ("Sim, como qualquer empresa", False),
          ("Sim, em dobro", False), ("Sim, mas só multa diária", False)]),
        ("As sanções administrativas da LGPD (arts. 52 a 54) passaram a vigorar em:", "Art. 65, I-A",
         "1º de agosto de 2021, por força da Lei nº 14.010/2020 (Art. 65, I-A). Os demais artigos vigoram desde "
         "18/09/2020 e a estrutura da ANPD desde 28/12/2018.", 3,
         [("1º de agosto de 2021", True), ("15 de agosto de 2018", False),
          ("18 de setembro de 2020", False), ("1º de janeiro de 2023", False)]),
        ("Pela Resolução CD/ANPD nº 18/2024, o encarregado:", "Res. CD/ANPD nº 18/2024, arts. 12, 14 e 19",
         "Pode ser pessoa natural ou jurídica (art. 12); não precisa de certificação ou formação específica (art. 14); "
         "pode acumular funções e atender mais de um agente, desde que sem conflito de interesse (art. 19).", 3,
         [("Pode ser pessoa jurídica, não exige certificação e pode acumular funções sem conflito", True),
          ("Deve ser advogado com certificação", False), ("Deve ser funcionário exclusivo", False),
          ("Deve ser registrado na ANPD", False)]),
        ("Uma empresa com sede no exterior que oferece serviços a pessoas localizadas no Brasil está sujeita à LGPD?",
         "Art. 3º, II",
         "Sim. A lei se aplica independentemente do país da sede quando a atividade tem por objetivo a oferta de bens "
         "ou serviços ou o tratamento de dados de indivíduos localizados no território nacional (Art. 3º, II).", 2,
         [("Sim, pela oferta a indivíduos localizados no Brasil", True), ("Não, só empresas brasileiras", False),
          ("Só se tiver filial no Brasil", False), ("Só se for empresa de tecnologia", False)]),
        ("A LGPD NÃO se aplica ao tratamento de dados feito por pessoa natural para:", "Art. 4º, I",
         "Fins exclusivamente particulares e não econômicos (Art. 4º, I) — por exemplo, a agenda de contatos pessoal.", 2,
         [("Fins exclusivamente particulares e não econômicos", True), ("Fins comerciais", False),
          ("Prestação de serviços", False), ("Cobrança de clientes", False)]),
    ],

    # ───────────────────────────── RH (Recursos Humanos) ─────────────────────────────
    "RH": [
        ("Um atestado médico entregue ao RH é classificado como:", "Art. 5º, II",
         "Dado pessoal sensível: dado referente à saúde (Art. 5º, II).", 1,
         [("Dado pessoal sensível", True), ("Dado anonimizado", False), ("Dado público", False),
          ("Dado não pessoal", False)]),
        ("A impressão digital coletada para o registro de ponto é:", "Art. 5º, II",
         "Dado biométrico, que a lei classifica como dado pessoal sensível (Art. 5º, II), sujeito às hipóteses do Art. 11.", 1,
         [("Dado biométrico, portanto sensível", True), ("Dado comum, como o nome", False),
          ("Dado anonimizado", False), ("Dado sem proteção legal", False)]),
        ("A informação de que um empregado é filiado a sindicato é:", "Art. 5º, II",
         "Dado pessoal sensível: 'filiação a sindicato ou a organização de caráter religioso, filosófico ou político' "
         "(Art. 5º, II).", 1,
         [("Dado pessoal sensível", True), ("Dado público por natureza", False),
          ("Dado comum", False), ("Dado irrelevante para a LGPD", False)]),
        ("A base legal típica para o RH tratar dados da folha de pagamento é:", "Art. 7º, II",
         "Cumprimento de obrigação legal ou regulatória pelo controlador (Art. 7º, II) — as obrigações trabalhistas e "
         "previdenciárias. Não depende de consentimento.", 2,
         [("Cumprimento de obrigação legal ou regulatória", True), ("Consentimento do empregado", False),
          ("Legítimo interesse do concorrente", False), ("Não é necessária base legal", False)]),
        ("O tratamento necessário para executar o contrato de trabalho de que o empregado é parte tem base no:",
         "Art. 7º, V",
         "Art. 7º, V: execução de contrato ou de procedimentos preliminares do qual seja parte o titular, a pedido dele.", 2,
         [("Art. 7º, V — execução de contrato", True), ("Art. 7º, X — proteção do crédito", False),
          ("Art. 7º, IV — pesquisa", False), ("Art. 7º, III — políticas públicas", False)]),
        ("Dados de saúde do empregado (sensíveis) podem ser tratados sem consentimento quando indispensáveis para:",
         "Art. 11, II, 'a'",
         "Cumprimento de obrigação legal ou regulatória pelo controlador (Art. 11, II, 'a') — uma das hipóteses de "
         "dispensa de consentimento para dados sensíveis.", 2,
         [("Cumprir obrigação legal ou regulatória", True), ("Atender ao legítimo interesse da empresa", False),
          ("Fazer marketing interno", False), ("Proteger o crédito", False)]),
        ("A hipótese de 'tutela da saúde' do Art. 11, II, 'f', aplica-se:", "Art. 11, II, 'f'",
         "Exclusivamente em procedimento realizado por profissionais de saúde, serviços de saúde ou autoridade "
         "sanitária. O RH, ao guardar um atestado, não a invoca — apoia-se na obrigação legal (alínea 'a').", 3,
         [("Só a profissionais, serviços de saúde ou autoridade sanitária", True),
          ("A qualquer departamento que receba um atestado", False),
          ("A todas as empresas com plano de saúde", False), ("Ao setor financeiro", False)]),
        ("Currículos de candidatos não contratados, encerrado o processo seletivo, devem:", "Arts. 15 e 16",
         "Ser eliminados após o término do tratamento (Art. 15, I; Art. 16), salvo conservação nas hipóteses do Art. 16 "
         "— por exemplo, cumprimento de obrigação legal.", 2,
         [("Ser eliminados, salvo hipótese legal de conservação", True), ("Ser guardados indefinidamente", False),
          ("Ser vendidos a agências de emprego", False), ("Ser publicados na intranet", False)]),
        ("Tratar dados de um candidato durante o processo seletivo, a pedido dele, pode ter base em:", "Art. 7º, V",
         "Procedimentos preliminares relacionados a contrato do qual o titular será parte, a pedido do titular "
         "(Art. 7º, V). O legítimo interesse também é possível, com teste de balanceamento (Guia ANPD 2024).", 3,
         [("Procedimentos preliminares a contrato, a pedido do titular", True),
          ("Proteção do crédito", False), ("Tutela da saúde", False), ("Políticas públicas", False)]),
        ("Dados de dependentes menores do empregado devem ser tratados:", "Art. 14 + Enunciado CD/ANPD nº 1/2023",
         "No melhor interesse da criança ou adolescente (Art. 14). O Enunciado nº 1/2023 admite qualquer hipótese dos "
         "arts. 7º ou 11, desde que observado e prevalecente o melhor interesse, avaliado no caso concreto.", 2,
         [("No melhor interesse do menor, com base legal dos arts. 7º ou 11", True),
          ("Livremente, como os do titular adulto", False), ("Somente com ordem judicial", False),
          ("Nunca; é proibido", False)]),
        ("Ao compartilhar dados do empregado com o plano de saúde, a empresa deve observar principalmente:",
         "Art. 6º, I e VI; Art. 9º",
         "Finalidade específica e transparência: o titular tem direito a informações claras sobre o uso compartilhado "
         "e sua finalidade (Art. 9º, V; Art. 6º, I e VI).", 2,
         [("Finalidade específica e transparência ao titular", True), ("Nada, é compartilhamento livre", False),
          ("Apenas aviso ao gestor", False), ("Autorização do sindicato", False)]),
        ("Operadoras de planos de saúde podem usar dados de saúde para selecionar riscos ao contratar beneficiários?",
         "Art. 11, § 5º",
         "Não. É vedado às operadoras de planos privados o tratamento de dados de saúde para seleção de riscos na "
         "contratação e na contratação ou exclusão de beneficiários (Art. 11, § 5º).", 3,
         [("Não, é vedado pela lei", True), ("Sim, livremente", False),
          ("Sim, com consentimento", False), ("Sim, para planos coletivos", False)]),
        ("Monitorar empregados com webcam e registro de teclas (keylogger), segundo o Guia de Legítimo Interesse da ANPD:",
         "Guia Orientativo Legítimo Interesse (ANPD, 2024)",
         "Não é admitido com base no legítimo interesse: interfere de forma excessiva e desproporcional nos direitos "
         "do titular, mesmo que a atividade tenha sido previamente informada (exemplo do próprio Guia).", 3,
         [("É excessivo e desproporcional, mesmo se informado previamente", True),
          ("É permitido se constar no contrato", False), ("É obrigatório para segurança", False),
          ("É permitido em home office", False)]),
        ("Publicar a lista de aniversariantes com a data de nascimento completa, sem avaliar necessidade, fere o princípio da:",
         "Art. 6º, I e III",
         "Necessidade (Art. 6º, III — mínimo necessário) e finalidade (Art. 6º, I): a data completa de nascimento "
         "excede o que a comemoração exige.", 2,
         [("Necessidade", True), ("Portabilidade", False), ("Gratuidade", False), ("Reciprocidade", False)]),
        ("Os empregados que tratam dados no exercício das suas funções são considerados operadores?",
         "Guia Orientativo Agentes de Tratamento (ANPD, v2.0, 2022)",
         "Não. Indivíduos subordinados (funcionários, equipes) atuam sob o poder diretivo do agente de tratamento; "
         "a organização é o agente. O operador deve ser entidade distinta do controlador (Guia de Agentes da ANPD).", 2,
         [("Não: atuam sob o poder diretivo da organização, que é o agente", True),
          ("Sim, cada um é um operador", False), ("Sim, se tiverem cargo de chefia", False),
          ("Sim, quando usam computador", False)]),
        ("Afixar a lista de CPFs dos empregados no mural da empresa viola principalmente:", "Art. 6º, III e VII",
         "Necessidade e segurança: exposição de dados a acessos não autorizados sem finalidade que a justifique "
         "(Art. 6º, III e VII; Art. 46).", 1,
         [("Necessidade e segurança", True), ("Portabilidade", False), ("Livre acesso", False),
          ("Não discriminação", False)]),
        ("Documentos trabalhistas de ex-empregados são conservados após o desligamento com base em:", "Art. 16, I",
         "Conservação autorizada para cumprimento de obrigação legal ou regulatória pelo controlador (Art. 16, I), "
         "pelos prazos que a legislação trabalhista e previdenciária exigir.", 2,
         [("Cumprimento de obrigação legal ou regulatória", True), ("Consentimento do ex-empregado", False),
          ("Curiosidade histórica", False), ("Não podem ser conservados", False)]),
        ("Um ex-empregado pede acesso aos seus dados. A declaração clara e completa deve ser fornecida em até:",
         "Art. 18, II; Art. 19, II",
         "15 dias, contados do requerimento (Art. 19, II); em formato simplificado, imediatamente (Art. 19, I).", 2,
         [("15 dias", True), ("48 horas", False), ("60 dias", False), ("6 meses", False)]),
        ("O ex-empregado pede a eliminação de dados que a empresa é obrigada por lei a guardar. O RH deve:",
         "Art. 16, I; Art. 18, § 4º, II",
         "Responder indicando as razões de fato ou de direito que impedem a providência (Art. 18, § 4º, II): a "
         "conservação é autorizada para cumprir obrigação legal (Art. 16, I).", 3,
         [("Responder com as razões legais que impedem a eliminação", True),
          ("Apagar tudo imediatamente", False), ("Ignorar o pedido", False), ("Cobrar uma taxa", False)]),
        ("A empresa terceirizada que processa a folha de pagamento é, em regra:", "Art. 5º, VII; Art. 39",
         "Operadora: trata dados em nome do controlador e deve seguir as instruções fornecidas por ele (Art. 39).", 2,
         [("Operadora, e deve seguir as instruções do controlador", True), ("Controladora conjunta sempre", False),
          ("Titular dos dados", False), ("Encarregada", False)]),
        ("Sobre o contrato entre o controlador e o operador, o Guia da ANPD orienta que:",
         "Guia Orientativo Agentes de Tratamento (ANPD, v2.0, 2022); Art. 39",
         "A LGPD não exige expressamente o contrato, mas ele se mostra uma boa prática — e o controlador deve "
         "verificar a observância das suas instruções (Art. 39).", 2,
         [("É boa prática, com instruções claras que o controlador verifica", True),
          ("É proibido pela LGPD", False), ("Só é necessário para órgãos públicos", False),
          ("Substitui a necessidade de base legal", False)]),
        ("Promover treinamento periódico de LGPD para os empregados relaciona-se à atribuição legal do encarregado de:",
         "Art. 41, § 2º, III",
         "Orientar os funcionários e os contratados a respeito das práticas de proteção de dados (Art. 41, § 2º, III).", 1,
         [("Orientar funcionários e contratados", True), ("Aplicar multas", False),
          ("Fiscalizar a ANPD", False), ("Aprovar contratações", False)]),
        ("Indicar o chefe do RH como encarregado, mantendo-o na chefia, pode configurar:",
         "Res. CD/ANPD nº 18/2024, art. 19; Guia Atuação do Encarregado (2024)",
         "Conflito de interesse: o Guia cita chefia de recursos humanos, TI, finanças ou saúde como posições que "
         "decidem meios e objetivos do tratamento, comprometendo a objetividade do encarregado.", 3,
         [("Conflito de interesse", True), ("Uma exigência da lei", False),
          ("A situação ideal, por conhecer os dados", False), ("Nada relevante", False)]),
        ("Uma planilha com salários foi enviada por e-mail a um destinatário errado. Isso é um incidente relevante?",
         "Res. CD/ANPD nº 15/2024, art. 5º, III",
         "Pode ser: dados financeiros são um dos critérios de risco ou dano relevante quando o incidente puder afetar "
         "significativamente direitos dos titulares (art. 5º). O controlador deve avaliar e registrar o incidente.", 3,
         [("Pode ser: dados financeiros são critério de risco relevante", True),
          ("Não, e-mail interno nunca é incidente", False), ("Só se houver mais de mil pessoas", False),
          ("Só se o destinatário reclamar", False)]),
        ("Vazamento de dados de saúde de empregados: em quanto tempo o controlador deve comunicar a ANPD?",
         "Res. CD/ANPD nº 15/2024, arts. 5º e 6º",
         "Dados sensíveis são critério de risco relevante (art. 5º, I); a comunicação deve ocorrer em 3 dias úteis do "
         "conhecimento de que o incidente afetou dados pessoais (art. 6º).", 2,
         [("3 dias úteis do conhecimento", True), ("72 horas", False), ("15 dias", False), ("Não precisa", False)]),
        ("Ao enviar holerites ou dados de salário por e-mail, o Guia de Segurança da ANPD recomenda:",
         "Guia Segurança da Informação para pequeno porte (ANPD, 2021)",
         "Conexões cifradas (TLS/HTTPS) ou aplicativos com criptografia fim a fim, inclusive para e-mails com "
         "salários ou prontuários.", 2,
         [("Usar conexões cifradas ou criptografia fim a fim", True), ("Enviar em texto simples", False),
          ("Usar pendrive sem senha", False), ("Publicar no grupo da equipe", False)]),
        ("Termos de confidencialidade (NDA) com funcionários são, segundo o Guia de Segurança da ANPD:",
         "Guia Segurança da Informação para pequeno porte (ANPD, 2021)",
         "Uma medida administrativa recomendada dentro do gerenciamento de contratos, ao lado de cláusulas de "
         "segurança com terceiros.", 1,
         [("Medida administrativa recomendada", True), ("Proibidos pela LGPD", False),
          ("Exigidos apenas para diretores", False), ("Substitutos do treinamento", False)]),
        ("Um gestor consulta o exame admissional de um subordinado sem necessidade para a função. Isso fere:",
         "Art. 6º, III; Guia Segurança (ANPD): menor privilégio",
         "O princípio da necessidade (Art. 6º, III) e o controle de acesso na proporção da necessidade ('menor "
         "privilégio', 'need to know') do Guia de Segurança da ANPD; dados de saúde são sensíveis (Art. 5º, II).", 2,
         [("A necessidade e o controle de acesso por menor privilégio", True), ("Nada, ele é o chefe", False),
          ("Apenas a etiqueta", False), ("A portabilidade", False)]),
        ("Ponto biométrico para todos os empregados: o que a Resolução CD/ANPD nº 2/2022 diz sobre o risco?",
         "Res. CD/ANPD nº 2/2022, art. 4º; Art. 38",
         "O uso de dados sensíveis é critério específico de alto risco (art. 4º, II, 'd'), combinado a um critério "
         "geral; a ANPD pode determinar a elaboração de RIPD (Art. 38).", 3,
         [("Dados sensíveis são critério de alto risco; a ANPD pode exigir RIPD", True),
          ("É sempre de baixo risco", False), ("É proibido", False), ("Dispensa qualquer avaliação", False)]),
        ("O que é pseudonimização, segundo a LGPD?", "Art. 13, § 4º",
         "Tratamento pelo qual um dado perde a associação direta ou indireta a um indivíduo, senão pelo uso de "
         "informação adicional mantida separadamente pelo controlador em ambiente controlado e seguro (Art. 13, § 4º).", 3,
         [("Perda da associação ao indivíduo, salvo com informação adicional guardada separadamente", True),
          ("Exclusão definitiva dos dados", False), ("Publicação sem o nome", False),
          ("O mesmo que anonimização", False)]),
        ("Pedir consentimento do empregado para processar a folha de pagamento é:", "Art. 7º, II; Art. 8º, § 4º",
         "Desnecessário e inadequado: a base é a obrigação legal (Art. 7º, II). Consentimento genérico é nulo "
         "(Art. 8º, § 4º) e a dispensa do consentimento não afasta as demais obrigações (Art. 7º, § 6º).", 2,
         [("Desnecessário: a base correta é a obrigação legal", True), ("Obrigatório por lei", False),
          ("Recomendado para todo tratamento", False), ("Exigido pela ANPD", False)]),
    ],

    # ───────────────────────────── FINANCEIRO ─────────────────────────────
    "FINANCEIRO": [
        ("Notas fiscais e documentos contábeis com dados pessoais são conservados com base em:", "Art. 7º, II; Art. 16, I",
         "Cumprimento de obrigação legal ou regulatória: a lei autoriza conservar os dados após o término do tratamento "
         "para esse fim (Art. 16, I).", 1,
         [("Cumprimento de obrigação legal ou regulatória", True), ("Consentimento do cliente", False),
          ("Marketing", False), ("Legítimo interesse do contador", False)]),
        ("Dados bancários e financeiros estão na lista de dados sensíveis do Art. 5º, II?", "Art. 5º, II; Res. CD/ANPD nº 15/2024, art. 5º, III",
         "Não estão na lista legal de sensíveis. Mas são critério de 'risco ou dano relevante' para comunicação de "
         "incidente (Res. 15/2024, art. 5º, III) e exigem proteção elevada (Art. 46).", 2,
         [("Não, mas são critério de risco relevante em incidentes", True), ("Sim, são sensíveis", False),
          ("Não, e não exigem proteção", False), ("Só os de pessoa jurídica", False)]),
        ("A hipótese legal específica para o tratamento voltado à proteção do crédito é:", "Art. 7º, X",
         "Proteção do crédito, inclusive quanto ao disposto na legislação pertinente (Art. 7º, X).", 2,
         [("Art. 7º, X — proteção do crédito", True), ("Art. 7º, IV — pesquisa", False),
          ("Art. 7º, VII — proteção da vida", False), ("Art. 11 — dados sensíveis", False)]),
        ("Dados sensíveis podem ser tratados, sem consentimento, para prevenção à fraude e segurança do titular quando:",
         "Art. 11, II, 'g'",
         "Nos processos de identificação e autenticação de cadastro em sistemas eletrônicos, resguardados os direitos "
         "do Art. 9º, exceto se prevalecerem direitos e liberdades fundamentais do titular (Art. 11, II, 'g').", 3,
         [("Na identificação e autenticação de cadastro em sistemas eletrônicos", True),
          ("Em qualquer análise de crédito", False), ("Para cobrança de dívidas", False),
          ("Para marketing de produtos financeiros", False)]),
        ("Antes de usar o legítimo interesse para análise antifraude com dados não sensíveis, a ANPD recomenda:",
         "Guia Orientativo Legítimo Interesse (ANPD, 2024)",
         "Realizar o teste de balanceamento (finalidade, necessidade, balanceamento e salvaguardas) para cada "
         "finalidade específica, documentando-o para demonstrar conformidade (Art. 6º, X; Art. 37).", 2,
         [("Realizar e documentar o teste de balanceamento", True), ("Pedir autorização à ANPD", False),
          ("Publicar os critérios no jornal", False), ("Nada; basta a decisão da diretoria", False)]),
        ("Enviar por e-mail uma planilha de clientes sem qualquer proteção configura:", "Art. 46",
         "Falha nas medidas técnicas e administrativas de segurança exigidas para proteger dados de acessos não "
         "autorizados e de comunicação acidental (Art. 46).", 1,
         [("Falha nas medidas de segurança do Art. 46", True), ("Boa prática de agilidade", False),
          ("Exigência fiscal", False), ("Anonimização", False)]),
        ("Expor o valor da dívida de um cliente a terceiros durante a cobrança fere:", "Art. 6º, I e VII",
         "A finalidade e a segurança (comunicação não autorizada), além da privacidade que a lei protege (Art. 1º).", 1,
         [("Finalidade e segurança", True), ("Nada, é permitido", False), ("Só a etiqueta comercial", False),
          ("A portabilidade", False)]),
        ("Dados bancários de clientes exigem, quanto à segurança:", "Art. 46; Guia Segurança (ANPD)",
         "Medidas aptas a proteger de acessos não autorizados: controle de acesso proporcional à necessidade, senhas "
         "complexas e, preferencialmente, autenticação multifator (Guia de Segurança da ANPD).", 1,
         [("Controle de acesso, senhas fortes e autenticação multifator", True), ("Nenhum cuidado especial", False),
          ("Publicação periódica", False), ("Compartilhamento livre", False)]),
        ("Após o fim da relação com o cliente e dos prazos legais de guarda, os dados financeiros devem ser:", "Art. 16",
         "Eliminados após o término do tratamento, salvo as hipóteses de conservação do Art. 16.", 2,
         [("Eliminados", True), ("Mantidos para sempre", False), ("Vendidos", False), ("Publicados", False)]),
        ("Ao consultar bureau de crédito sobre um cliente, a empresa deve garantir:", "Art. 6º, VI; Art. 7º, X",
         "Base legal adequada (proteção do crédito, Art. 7º, X) e transparência: informações claras e acessíveis "
         "sobre o tratamento (Art. 6º, VI).", 2,
         [("Base legal adequada e transparência ao titular", True), ("Sigilo total sobre a consulta", False),
          ("Autorização verbal apenas", False), ("Nada; consulta é livre", False)]),
        ("A contabilidade externa que recebe dados de clientes e empregados para escrituração é:", "Art. 5º, VII; Art. 39",
         "Operadora: trata os dados em nome do controlador e deve seguir suas instruções (Art. 39). O Guia da ANPD "
         "recomenda contrato com cláusulas de proteção de dados.", 2,
         [("Operadora, que deve seguir as instruções do controlador", True), ("Titular", False),
          ("Autoridade nacional", False), ("Controladora exclusiva", False)]),
        ("Uma mensagem de cobrança que revela a dívida a um familiar do devedor viola:", "Art. 6º, VII",
         "A segurança: os dados devem ser protegidos de comunicação ou difusão não autorizada (Art. 6º, VII; Art. 46).", 2,
         [("A segurança (comunicação não autorizada)", True), ("A gratuidade", False),
          ("A qualidade dos dados", False), ("Nada", False)]),
        ("O cliente quer saber com quais entidades a empresa compartilhou seus dados. Ele tem esse direito?", "Art. 18, VII",
         "Sim: informação das entidades públicas e privadas com as quais o controlador realizou uso compartilhado "
         "de dados (Art. 18, VII).", 2,
         [("Sim, é direito do titular (Art. 18, VII)", True), ("Não, é segredo comercial absoluto", False),
          ("Só com ordem judicial", False), ("Só se pagar uma taxa", False)]),
        ("O direito de portabilidade dos dados (Art. 18, V) é exercido:", "Art. 18, V e § 7º",
         "Mediante requisição expressa, de acordo com a regulamentação da autoridade nacional, observados os segredos "
         "comercial e industrial; não inclui dados já anonimizados (§ 7º).", 2,
         [("Mediante requisição expressa, conforme regulamentação da ANPD", True),
          ("Automaticamente, todo mês", False), ("Apenas por ordem judicial", False), ("Nunca", False)]),
        ("Um cliente teve crédito negado por decisão unicamente automatizada. Ele pode:", "Art. 20",
         "Solicitar a revisão da decisão, inclusive as destinadas a definir perfil de crédito (Art. 20, caput).", 2,
         [("Solicitar a revisão da decisão", True), ("Exigir aprovação automática", False),
          ("Nada; a decisão é definitiva", False), ("Processar o operador do sistema apenas", False)]),
        ("Sobre os critérios da decisão automatizada de crédito, o controlador deve:", "Art. 20, § 1º",
         "Fornecer, sempre que solicitadas, informações claras e adequadas sobre os critérios e procedimentos, "
         "observados os segredos comercial e industrial (Art. 20, § 1º).", 3,
         [("Informar critérios e procedimentos, observados os segredos comercial e industrial", True),
          ("Manter tudo em sigilo absoluto", False), ("Entregar o código-fonte", False),
          ("Nada; não há dever de informar", False)]),
        ("No cálculo da multa simples, o faturamento considerado é:", "Art. 52, II",
         "O da pessoa jurídica, grupo ou conglomerado no Brasil, no último exercício, excluídos os tributos — até 2%, "
         "limitado a R$ 50 milhões por infração (Art. 52, II).", 2,
         [("Do último exercício no Brasil, excluídos os tributos", True), ("Mundial, com tributos", False),
          ("Apenas do mês da infração", False), ("Do faturamento projetado", False)]),
        ("A multa diária da LGPD:", "Art. 52, III",
         "Observa o mesmo limite total da multa simples (R$ 50 milhões por infração) — Art. 52, III; Res. 4/2023, "
         "art. 16.", 3,
         [("Observa o mesmo teto total da multa simples", True), ("Não tem limite", False),
          ("É fixa em R$ 1.000", False), ("Só se aplica a bancos", False)]),
        ("Pela dosimetria da ANPD, cessar a infração ANTES de a ANPD instaurar procedimento reduz a multa em:",
         "Res. CD/ANPD nº 4/2023, art. 13, I, 'a'",
         "75%. Após o procedimento preparatório, 50%; após o processo sancionador, 30% (art. 13, I).", 3,
         [("75%", True), ("10%", False), ("25%", False), ("100%", False)]),
        ("Cada reincidência específica agrava a multa, pela Resolução CD/ANPD nº 4/2023, em:",
         "Res. CD/ANPD nº 4/2023, art. 12, I",
         "10% por caso, até o limite de 40% (art. 12, I). Reincidência específica é repetir infração ao mesmo "
         "dispositivo em 5 anos (art. 2º).", 3,
         [("10% por caso, até 40%", True), ("50% por caso", False), ("1% por caso", False), ("Não agrava", False)]),
        ("Prazo para pagar a multa aplicada pela ANPD e efeito da renúncia ao recurso:",
         "Res. CD/ANPD nº 4/2023, arts. 17 e 18",
         "20 dias úteis da ciência da decisão (em dobro para pequeno porte); renúncia expressa ao recurso com "
         "pagamento no prazo dá redução de 25%.", 3,
         [("20 dias úteis; renúncia ao recurso reduz 25%", True), ("30 dias corridos; sem redução", False),
          ("5 dias; redução de 50%", False), ("1 ano; sem redução", False)]),
        ("O produto das multas aplicadas pela ANPD é destinado ao:", "Art. 52, § 5º",
         "Fundo de Defesa de Direitos Difusos (Art. 52, § 5º).", 3,
         [("Fundo de Defesa de Direitos Difusos", True), ("Tesouro do Estado", False),
          ("Caixa da própria ANPD", False), ("Titular prejudicado", False)]),
        ("Vazamento de dados de cartão e conta de clientes: qual o prazo de comunicação à ANPD?",
         "Res. CD/ANPD nº 15/2024, arts. 5º, III, e 6º",
         "Dados financeiros são critério de risco relevante; a comunicação à ANPD e aos titulares é em 3 dias úteis "
         "do conhecimento de que afetou dados pessoais.", 2,
         [("3 dias úteis", True), ("72 horas", False), ("10 dias corridos", False), ("Não há prazo", False)]),
        ("Sobre cópias de segurança (backups) com dados pessoais, o Guia de Segurança da ANPD recomenda:",
         "Guia Segurança da Informação para pequeno porte (ANPD, 2021)",
         "Backups regulares, completos, armazenados em locais seguros e distintos dos dispositivos principais, e que "
         "não sejam sincronizados online em tempo real (proteção contra ransomware).", 2,
         [("Regulares, em local distinto e sem sincronização em tempo real", True),
          ("Só no mesmo servidor", False), ("Apenas em pendrive", False), ("Dispensáveis", False)]),
        ("Pendrives e HDs externos com dados pessoais, segundo o Guia de Segurança da ANPD:", "Guia Segurança (ANPD, 2021)",
         "Devem ser evitados; se imprescindíveis, inventariados, com dados cifrados e guardados em local seguro.", 2,
         [("Evitar; se usar, inventariar, cifrar e guardar em local seguro", True),
          ("Usar livremente", False), ("Só com etiqueta", False), ("Compartilhar entre equipes", False)]),
        ("O CNPJ e a razão social de um cliente pessoa jurídica são dados pessoais?", "Art. 5º, I e V",
         "Não: referem-se a pessoa jurídica. Já os dados dos sócios, representantes e contatos (pessoas naturais) são "
         "dados pessoais.", 2,
         [("Não, mas os dados dos sócios e contatos são", True), ("Sim, todos", False),
          ("Sim, e são sensíveis", False), ("Depende do faturamento", False)]),
        ("Para compartilhar com outro controlador dados obtidos com consentimento, o controlador deve:", "Art. 7º, § 5º",
         "Obter consentimento específico do titular para esse fim, ressalvadas as hipóteses de dispensa (Art. 7º, § 5º).", 3,
         [("Obter consentimento específico para o compartilhamento", True), ("Nada; o primeiro consentimento basta", False),
          ("Avisar a ANPD", False), ("Cobrar do parceiro", False)]),
        ("A troca de bancos de dados pessoais entre duas empresas privadas é chamada, na LGPD, de:", "Art. 5º, XVI",
         "Uso compartilhado de dados: comunicação, difusão, transferência internacional, interconexão ou tratamento "
         "compartilhado de bancos de dados, inclusive entre entes privados (Art. 5º, XVI).", 3,
         [("Uso compartilhado de dados", True), ("Anonimização", False), ("Bloqueio", False), ("Portabilidade", False)]),
        ("Pagar um fornecedor no exterior enviando dados pessoais para lá exige, pela Resolução CD/ANPD nº 19/2024:",
         "Res. CD/ANPD nº 19/2024, art. 9º; Art. 33",
         "Uma hipótese legal do Art. 7º ou 11 E um mecanismo válido do Art. 33 — por exemplo, o inciso IX admite a "
         "transferência necessária às hipóteses de obrigação legal, contrato e exercício de direitos.", 3,
         [("Base legal E um mecanismo do Art. 33", True), ("Apenas o câmbio aprovado", False),
          ("Nada, pagamento não é tratamento", False), ("Autorização do Banco Central", False)]),
        ("As atividades de tratamento do Financeiro (faturamento, cobrança) devem constar do:", "Art. 37",
         "Registro das operações de tratamento (ROPA), obrigatório para controlador e operador (Art. 37).", 1,
         [("Registro das operações de tratamento (ROPA)", True), ("Balanço patrimonial", False),
          ("Livro de ponto", False), ("Site da ANPD", False)]),
        ("Um cliente reclama do uso dos seus dados. Quem, na empresa, tem a atribuição legal de aceitar e tratar a reclamação?",
         "Art. 41, § 2º, I",
         "O encarregado: aceitar reclamações e comunicações dos titulares, prestar esclarecimentos e adotar providências.", 1,
         [("O encarregado", True), ("O gerente comercial", False), ("O contador", False), ("A ANPD", False)]),
    ],
}
