"""Banco de questões — parte B: MARKETING, TI, ATENDIMENTO e JURIDICO.

Fontes: as mesmas da parte A (Lei nº 13.709/2018 compilada; Resoluções CD/ANPD 2/2022,
4/2023, 15/2024, 18/2024, 19/2024 e 32/2026; Enunciado 1/2023; Guias Orientativos da ANPD).
"""

QUESTOES_B = {
    # ───────────────────────────── MARKETING e Vendas ─────────────────────────────
    "MARKETING": [
        ("O consentimento válido para marketing deve ser uma manifestação:", "Art. 5º, XII",
         "Livre, informada e inequívoca, para finalidade determinada (Art. 5º, XII). O Guia de Cookies da ANPD "
         "acrescenta: manifestação clara e positiva, nunca inferida de omissão.", 1,
         [("Livre, informada e inequívoca", True), ("Presumida pela navegação", False),
          ("Genérica, para qualquer finalidade", False), ("Permanente e irrevogável", False)]),
        ("Disparar e-mail marketing para uma base de contatos comprada de terceiros:", "Art. 7º, § 5º; Art. 6º, I",
         "Carece de hipótese legal: quem obteve consentimento e quer compartilhar com outro controlador precisa de "
         "consentimento específico para isso (Art. 7º, § 5º), e a finalidade deve ter sido informada ao titular (Art. 6º, I).", 2,
         [("Carece de hipótese legal e fere a finalidade informada", True), ("É prática recomendada", False),
          ("É permitido se a base for antiga", False), ("Não envolve dados pessoais", False)]),
        ("Para cookies NÃO necessários (rastreamento, publicidade), o Guia da ANPD aponta como base mais apropriada:",
         "Guia Orientativo Cookies (ANPD, 2022)",
         "O consentimento: 'o recurso ao consentimento será mais apropriado quando a coleta for realizada por cookies "
         "não necessários', especialmente os de publicidade.", 2,
         [("O consentimento", True), ("A obrigação legal", False), ("A proteção do crédito", False),
          ("A tutela da saúde", False)]),
        ("Para cookies estritamente necessários ao funcionamento do site, o Guia da ANPD orienta que:",
         "Guia Orientativo Cookies (ANPD, 2022); Art. 10",
         "O legítimo interesse poderá ser a hipótese apropriada; NÃO é apropriado usar consentimento, pois não há "
         "condições para manifestação livre (o site não funciona sem eles).", 3,
         [("O legítimo interesse pode ser a base; consentimento não é apropriado", True),
          ("Exigem consentimento prévio", False), ("São proibidos", False), ("Dispensam qualquer base", False)]),
        ("Um banner de cookies com um único botão 'Estou de acordo', sem opção de gerenciar ou rejeitar, é:",
         "Guia Orientativo Cookies (ANPD, 2022)",
         "Incompatível com a LGPD, segundo exemplo do próprio Guia: o primeiro nível deve permitir rejeitar todos os "
         "cookies não necessários, com fácil visualização.", 2,
         [("Incompatível com a LGPD", True), ("A prática recomendada", False),
          ("Suficiente se houver política de privacidade", False), ("Obrigatório", False)]),
        ("Caixas pré-marcadas e a presunção de que 'continuar navegando' é consentir são, para a ANPD:",
         "Guia Orientativo Cookies (ANPD, 2022)",
         "Não recomendáveis: o consentimento não pode ser tácito nem obtido por pré-seleção; exige manifestação "
         "clara e positiva.", 2,
         [("Não recomendáveis: consentimento não pode ser tácito", True), ("Válidas se avisadas", False),
          ("Obrigatórias", False), ("Indiferentes", False)]),
        ("O banner de PRIMEIRO nível, segundo o Guia da ANPD, deve:", "Guia Orientativo Cookies (ANPD, 2022)",
         "Disponibilizar botão que permita rejeitar todos os cookies não necessários, de fácil visualização, e link "
         "para o exercício de direitos; o segundo nível permite consentir por finalidade.", 2,
         [("Ter botão para rejeitar todos os não necessários, bem visível", True),
          ("Destacar apenas o botão 'Aceitar'", False), ("Listar cada cookie individualmente", False),
          ("Estar apenas em inglês", False)]),
        ("A revogação do consentimento de cookies deve ser oferecida:", "Guia Cookies (ANPD); Art. 8º, § 5º",
         "Por procedimento simplificado e gratuito, similar ao usado para obtê-lo (Guia); a lei garante revogação a "
         "qualquer momento, gratuita e facilitada (Art. 8º, § 5º).", 2,
         [("De forma simplificada e gratuita, similar à obtenção", True), ("Apenas por carta registrada", False),
          ("Somente ao encarregado", False), ("Não precisa ser oferecida", False)]),
        ("Usar o legítimo interesse para cookies de publicidade que formam perfis de usuários é, para a ANPD:",
         "Guia Orientativo Cookies (ANPD, 2022)",
         "Dificilmente apropriado — especialmente cookies de terceiros e formação de perfis; o consentimento é a base "
         "mais adequada para publicidade.", 3,
         [("Dificilmente apropriado; consentimento é a base indicada", True), ("Sempre adequado", False),
          ("Obrigatório", False), ("Indiferente", False)]),
        ("Cookies analíticos de medição de audiência podem se apoiar no legítimo interesse quando:",
         "Guia Orientativo Cookies (ANPD, 2022)",
         "Os dados são agregados, sem combinação com outros rastreadores e sem formação de perfis de usuários.", 3,
         [("Os dados são agregados e sem formação de perfis", True), ("Servem para anúncios personalizados", False),
          ("Vêm de terceiros", False), ("Duram vários anos", False)]),
        ("Cookies 'de terceiros', pelo Guia da ANPD, são os:", "Guia Orientativo Cookies (ANPD, 2022)",
         "Criados por um domínio diferente daquele que o titular está visitando (por oposição aos próprios/primários).", 1,
         [("Criados por domínio diferente do site visitado", True), ("Usados por mais de três pessoas", False),
          ("Instalados há mais de três dias", False), ("Aprovados pela ANPD", False)]),
        ("Sobre a duração dos cookies persistentes, o Guia da ANPD recomenda:", "Guia Orientativo Cookies (ANPD, 2022)",
         "Limitar a duração no tempo tanto quanto possível; períodos de retenção indeterminados, excessivos ou "
         "desproporcionais não são compatíveis com a LGPD.", 2,
         [("Limitar a duração; retenção indeterminada é incompatível", True), ("Manter por prazo indefinido", False),
          ("Fixar sempre em 10 anos", False), ("Não há orientação", False)]),
        ("Dados usados para formar o perfil comportamental de uma pessoa identificada:", "Art. 12, § 2º",
         "Podem ser considerados dados pessoais para os fins da LGPD (Art. 12, § 2º), mesmo que parte deles pareça "
         "anônima.", 2,
         [("Podem ser considerados dados pessoais", True), ("Nunca são dados pessoais", False),
          ("São dados públicos", False), ("Só se incluírem o CPF", False)]),
        ("Ofertas decididas unicamente por algoritmo com base no perfil de consumo do cliente dão a ele o direito de:",
         "Art. 20",
         "Solicitar a revisão da decisão, inclusive as destinadas a definir perfil de consumo (Art. 20).", 2,
         [("Solicitar a revisão da decisão", True), ("Receber a oferta obrigatoriamente", False),
          ("Nada", False), ("Processar o algoritmo", False)]),
        ("O descadastro (opt-out) de campanhas baseadas em consentimento decorre de qual regra?", "Art. 8º, § 5º",
         "O consentimento pode ser revogado a qualquer momento, por procedimento gratuito e facilitado (Art. 8º, § 5º).", 1,
         [("Revogação do consentimento, gratuita e facilitada", True), ("Cortesia opcional", False),
          ("Exigência do Procon apenas", False), ("Regra do provedor de e-mail", False)]),
        ("A empresa quer usar os dados coletados com consentimento para uma finalidade nova e incompatível. Ela deve:",
         "Art. 9º, § 2º",
         "Informar previamente o titular sobre a mudança de finalidade, podendo ele revogar o consentimento se "
         "discordar (Art. 9º, § 2º).", 3,
         [("Informar previamente; o titular pode revogar", True), ("Usar sem avisar", False),
          ("Apenas atualizar a política interna", False), ("Pedir autorização à ANPD", False)]),
        ("Se o consentimento for colhido por escrito em um contrato, ele deve:", "Art. 8º, § 1º",
         "Constar de cláusula destacada das demais cláusulas contratuais (Art. 8º, § 1º).", 2,
         [("Constar de cláusula destacada", True), ("Ficar diluído nas condições gerais", False),
          ("Ser verbal", False), ("Ser assinado pela ANPD", False)]),
        ("Condicionar o uso do site ao aceite integral de todos os cookies, sem opções efetivas, é:",
         "Guia Orientativo Cookies (ANPD, 2022)",
         "Consentimento 'forçado', não compatível com a LGPD segundo o Guia: o titular precisa de possibilidade "
         "efetiva de aceitar ou recusar sem consequências negativas.", 2,
         [("Consentimento forçado, incompatível com a LGPD", True), ("Prática aceita", False),
          ("Obrigatório para segurança", False), ("Válido se a política avisar", False)]),
        ("Um aplicativo educativo exibe a crianças publicidade de alimentos ultraprocessados. Pelo Guia da ANPD:",
         "Guia Legítimo Interesse (ANPD, 2024); Art. 14",
         "Não há legítima expectativa nem melhor interesse da criança — exemplo do próprio Guia de tratamento que não "
         "pode se apoiar no legítimo interesse.", 3,
         [("Não há legítima expectativa nem melhor interesse: inadmissível por legítimo interesse", True),
          ("É permitido com aviso aos pais", False), ("É neutro para a LGPD", False), ("É incentivado", False)]),
        ("Coletar dados de crianças em uma promoção exige, pela regra do Art. 14:", "Art. 14, §§ 1º e 4º",
         "Consentimento específico e em destaque de pelo menos um dos pais ou do responsável legal (§ 1º), sem "
         "condicionar a participação ao fornecimento de dados além dos estritamente necessários (§ 4º).", 2,
         [("Consentimento de um dos pais ou responsável, sem exigir dados além do necessário", True),
          ("Só o consentimento da própria criança", False), ("Nenhuma exigência", False),
          ("Autorização escolar", False)]),
        ("Dados tornados manifestamente públicos pelo titular (ex.: perfil aberto) podem ser tratados:", "Art. 7º, § 4º",
         "Com dispensa do consentimento, resguardados os direitos do titular e os princípios da lei (Art. 7º, § 4º) — "
         "não é 'terra de ninguém'.", 3,
         [("Sem consentimento, mas respeitando direitos e princípios", True), ("Livremente, sem limites", False),
          ("Nunca", False), ("Só com ordem judicial", False)]),
        ("Ao avaliar se um tratamento por legítimo interesse está dentro da 'legítima expectativa' do titular, a ANPD considera:",
         "Guia Legítimo Interesse (ANPD, 2024)",
         "A relação prévia com o titular, a fonte e a forma da coleta, o contexto e o período, e a compatibilidade da "
         "finalidade — o tratamento deve ser razoavelmente o esperado pelo titular naquele contexto.", 3,
         [("Relação prévia, fonte da coleta, contexto e compatibilidade da finalidade", True),
          ("Apenas o lucro esperado", False), ("A opinião do gerente de marketing", False),
          ("O tamanho da empresa", False)]),
        ("Divulgar aos alunos a campanha de uma escola de idiomas parceira (interesse de terceiro) é possível, pelo Guia da ANPD, se:",
         "Guia Legítimo Interesse (ANPD, 2024); Art. 7º, IX",
         "Houver teste de balanceamento e mecanismo de descadastramento — exemplo do Guia de legítimo interesse de "
         "terceiro, que exige ônus argumentativo adicional.", 3,
         [("Houver teste de balanceamento e opção de descadastro", True), ("Nunca", False),
          ("Sempre, sem formalidade", False), ("Só com consentimento notarial", False)]),
        ("Enviar promoções dos próprios produtos a clientes atuais, com opção de descadastro, pode se apoiar em:",
         "Art. 10, I e II; Guia Legítimo Interesse (ANPD, 2024)",
         "Legítimo interesse: apoio e promoção das atividades do controlador (Art. 10, I), respeitadas as legítimas "
         "expectativas e com salvaguardas como o descadastramento (exemplo do Guia).", 2,
         [("Legítimo interesse, com salvaguardas e descadastro", True), ("Tutela da saúde", False),
          ("Proteção do crédito", False), ("Políticas públicas", False)]),
        ("O titular pode se opor a um tratamento feito com base em hipótese de dispensa de consentimento?", "Art. 18, § 2º",
         "Sim, em caso de descumprimento da lei (Art. 18, § 2º). O Guia da ANPD acrescenta que, se a oposição não "
         "for atendida, o titular pode peticionar contra o controlador perante a ANPD.", 2,
         [("Sim, em caso de descumprimento da lei, e pode peticionar à ANPD", True), ("Não, nunca", False),
          ("Só se tiver consentido antes", False), ("Só judicialmente", False)]),
        ("Entre as informações que devem estar acessíveis ao titular (Art. 9º) estão:", "Art. 9º",
         "Finalidade específica, forma e duração do tratamento, identificação e contato do controlador, uso "
         "compartilhado e sua finalidade, responsabilidades dos agentes e os direitos do titular.", 2,
         [("Finalidade, duração, identificação e contato do controlador, compartilhamento e direitos", True),
          ("Apenas o nome do site", False), ("O faturamento da campanha", False), ("A lista de clientes", False)]),
        ("A política de cookies deve informar, segundo o Guia da ANPD:", "Guia Orientativo Cookies (ANPD, 2022); Art. 9º",
         "As finalidades específicas, o período de retenção e se há compartilhamento com terceiros, entre outros "
         "aspectos do Art. 9º — e pode ficar no aviso de privacidade, em página própria ou no banner.", 1,
         [("Finalidades, retenção e compartilhamento com terceiros", True), ("Apenas o nome da agência", False),
          ("O código dos cookies", False), ("Nada, é opcional", False)]),
        ("Qual a diferença entre política de privacidade e aviso de privacidade, pelo Guia do Encarregado da ANPD?",
         "Guia Atuação do Encarregado (ANPD, 2024)",
         "A política de privacidade é documento interno de governança; o aviso de privacidade é o documento público, "
         "voltado ao titular.", 2,
         [("Política é interna; aviso é o documento público ao titular", True), ("São sinônimos", False),
          ("Aviso é interno; política é pública", False), ("Nenhum é necessário", False)]),
        ("Usar uma ferramenta de e-mail marketing hospedada na União Europeia envolve transferência internacional. Ela é permitida porque:",
         "Art. 33, I; Res. CD/ANPD nº 32/2026; Res. nº 19/2024, art. 9º",
         "A ANPD reconheceu a União Europeia e o EEE como adequados (Res. nº 32/2026), mecanismo do Art. 33, I — mas "
         "ainda é preciso uma hipótese legal do Art. 7º ou 11 (Res. 19/2024, art. 9º).", 3,
         [("Há decisão de adequação da UE, além da base legal do Art. 7º", True), ("Não é permitida", False),
          ("Basta o contrato com o fornecedor", False), ("Não é transferência internacional", False)]),
        ("Vazou uma lista de e-mails de uma promoção infantil. Isso é incidente com risco relevante?",
         "Res. CD/ANPD nº 15/2024, art. 5º, II",
         "Dados de crianças, adolescentes ou idosos são critério de risco ou dano relevante (art. 5º, II) quando o "
         "incidente puder afetar significativamente direitos dos titulares — avaliar, registrar e comunicar em 3 dias úteis.", 2,
         [("Sim: dados de crianças são critério de risco relevante", True), ("Não, e-mail não é dado pessoal", False),
          ("Só se houver senha junto", False), ("Só se a ANPD perguntar", False)]),
    ],

    # ───────────────────────────── TI e Segurança da Informação ─────────────────────────────
    "TI": [
        ("O Art. 46 da LGPD exige dos agentes de tratamento:", "Art. 46",
         "Medidas de segurança, técnicas e administrativas, aptas a proteger os dados de acessos não autorizados e de "
         "situações acidentais ou ilícitas de destruição, perda, alteração, comunicação ou difusão.", 1,
         [("Medidas técnicas e administrativas de segurança", True), ("Apenas um antivírus", False),
          ("Somente política escrita", False), ("Certificação ISO obrigatória", False)]),
        ("O provedor de nuvem que armazena dados em nome da empresa é:", "Art. 5º, VII",
         "Operador: realiza o tratamento em nome do controlador (Art. 5º, VII) e deve seguir suas instruções (Art. 39).", 1,
         [("Operador", True), ("Controlador", False), ("Titular", False), ("Encarregado", False)]),
        ("A empresa de nuvem contratada pelo OPERADOR (não pelo controlador) para ajudá-lo é, pelo Guia da ANPD:",
         "Guia Orientativo Agentes de Tratamento (ANPD, v2.0, 2022)",
         "Suboperadora: contratada pelo operador para auxiliá-lo, com relação direta com o operador; pode ser "
         "equiparada ao operador nas atividades que executa. Recomenda-se autorização do controlador.", 3,
         [("Suboperadora, equiparável ao operador nas suas atividades", True), ("Controladora conjunta", False),
          ("Titular", False), ("Fora do alcance da LGPD", False)]),
        ("Conceder a cada usuário apenas os acessos necessários à sua função é o princípio de:",
         "Guia Segurança da Informação (ANPD, 2021)",
         "Menor privilégio (need to know): permissões na proporção da necessidade, com autenticação, autorização e "
         "auditoria.", 1,
         [("Menor privilégio (need to know)", True), ("Acesso total", False), ("Livre acesso público", False),
          ("Portabilidade", False)]),
        ("Sobre autenticação, o Guia de Segurança da ANPD recomenda:", "Guia Segurança da Informação (ANPD, 2021)",
         "Preferencialmente autenticação multifator (MFA), senhas complexas, sem compartilhar contas e sem manter "
         "senhas padrão de fornecedores.", 1,
         [("Autenticação multifator e senhas fortes, sem contas compartilhadas", True),
          ("Senha única para a equipe", False), ("Senha padrão do fornecedor", False), ("Acesso sem senha", False)]),
        ("Logs de acesso são importantes, à luz da Resolução CD/ANPD nº 15/2024, para:", "Res. CD/ANPD nº 15/2024, art. 10; Art. 48",
         "Apurar e registrar incidentes: o controlador deve manter registro do incidente com circunstâncias, dados "
         "afetados, avaliação de risco e medidas — e responder à ANPD com a causa principal.", 2,
         [("Investigar, registrar e comunicar incidentes", True), ("Ocupar espaço em disco", False),
          ("Marketing", False), ("Nada relevante", False)]),
        ("O Guia de Segurança da ANPD cita a criptografia como exemplo de técnica de:", "Guia Segurança (ANPD, 2021); Art. 13, § 4º",
         "Pseudonimização de dados armazenados, recomendada especialmente para dados sensíveis.", 2,
         [("Pseudonimização dos dados armazenados", True), ("Anonimização irreversível", False),
          ("Eliminação", False), ("Portabilidade", False)]),
        ("Backups com dados pessoais devem, segundo a ANPD:", "Guia Segurança da Informação (ANPD, 2021)",
         "Ser regulares e completos, guardados em locais seguros e distintos dos dispositivos principais, e não "
         "sincronizados online em tempo real (contra ransomware).", 2,
         [("Ficar em local distinto e não sincronizados em tempo real", True), ("Ficar no mesmo servidor", False),
          ("Ser feitos uma vez por ano", False), ("Ser públicos", False)]),
        ("Manter sistemas atualizados com as correções (patches) dos fornecedores é, para a ANPD:", "Guia Segurança (ANPD, 2021)",
         "Medida técnica contra vulnerabilidades, ao lado de antivírus atualizado com varreduras periódicas.", 1,
         [("Medida técnica contra vulnerabilidades", True), ("Opcional", False), ("Risco desnecessário", False),
          ("Só para servidores", False)]),
        ("Sobre o antivírus nas estações, o Guia da ANPD recomenda que:", "Guia Segurança (ANPD, 2021)",
         "Esteja atualizado, com varreduras periódicas e sem possibilidade de desativação pelos usuários.", 2,
         [("Não possa ser desativado pelos usuários", True), ("Seja opcional", False),
          ("Fique desligado para desempenho", False), ("Rode só na sexta", False)]),
        ("O que é 'incidente de segurança', pela Resolução CD/ANPD nº 15/2024?", "Res. CD/ANPD nº 15/2024, art. 3º, XII",
         "Qualquer evento adverso confirmado, relacionado à violação das propriedades de confidencialidade, "
         "integridade, disponibilidade e autenticidade da segurança de dados pessoais.", 2,
         [("Evento adverso confirmado que viola confidencialidade, integridade, disponibilidade ou autenticidade", True),
          ("Qualquer erro de sistema", False), ("Só ataque hacker externo", False), ("Só perda física de papel", False)]),
        ("A mera existência de uma vulnerabilidade em um sistema é um incidente de segurança?", "Página CIS da ANPD (gov.br/anpd)",
         "Não. Segundo a ANPD, a mera existência de vulnerabilidade não constitui incidente — incidente é evento "
         "adverso confirmado.", 3,
         [("Não: vulnerabilidade não é incidente; incidente é evento confirmado", True), ("Sim, sempre", False),
          ("Sim, se for crítica", False), ("Sim, se a ANPD souber", False)]),
        ("Um incidente que envolveu somente dados anonimizados precisa ser comunicado à ANPD?", "Página CIS da ANPD; Art. 12",
         "Não: incidentes que envolvam somente dados anonimizados ou não relacionados a pessoas identificáveis não "
         "precisam ser comunicados (orientação oficial da ANPD).", 3,
         [("Não", True), ("Sim, sempre", False), ("Sim, em 3 dias úteis", False), ("Sim, ao Procon", False)]),
        ("O prazo de 3 dias úteis para comunicar o incidente à ANPD conta a partir de:", "Res. CD/ANPD nº 15/2024, art. 6º, § 1º",
         "Do conhecimento pelo controlador de que o incidente afetou dados pessoais (art. 6º, § 1º); em dobro para "
         "agentes de pequeno porte (§ 8º).", 2,
         [("Do conhecimento de que o incidente afetou dados pessoais", True), ("Da data do ataque", False),
          ("Do boletim de ocorrência", False), ("Do fim da investigação", False)]),
        ("O operador detecta um incidente nos dados que trata para o controlador. Ele deve:", "Página CIS da ANPD; Art. 48",
         "Informar o fato ao controlador sem demora injustificada e fornecer as informações — a comunicação à ANPD "
         "e aos titulares é obrigação do controlador (Art. 48).", 2,
         [("Informar o controlador sem demora; a comunicação à ANPD é do controlador", True),
          ("Comunicar a ANPD por conta própria e não avisar o controlador", False),
          ("Esperar o controlador descobrir", False), ("Apagar os logs", False)]),
        ("A comunicação de incidente à ANPD deve conter, entre outros:", "Res. CD/ANPD nº 15/2024, art. 6º, § 2º",
         "A natureza e categoria dos dados; o número de titulares (discriminando crianças, adolescentes e idosos); as "
         "medidas antes e depois; os riscos; as datas do incidente e do conhecimento; a causa principal; os dados do "
         "encarregado.", 3,
         [("Dados afetados, número de titulares, medidas, riscos, datas e causa principal", True),
          ("Apenas o nome da empresa", False), ("A lista completa dos titulares", False),
          ("O código-fonte do sistema", False)]),
        ("Por quanto tempo o controlador deve manter o registro de um incidente, inclusive dos não comunicados?",
         "Res. CD/ANPD nº 15/2024, art. 10",
         "Pelo prazo mínimo de cinco anos, contado da data do registro, com data de conhecimento, circunstâncias, "
         "dados, número de titulares, avaliação de risco, medidas e motivos de eventual não comunicação.", 3,
         [("No mínimo 5 anos", True), ("6 meses", False), ("Até o fim do ano", False), ("Não precisa registrar", False)]),
        ("Se for inviável comunicar cada titular afetado individualmente, a Resolução nº 15/2024 admite:",
         "Res. CD/ANPD nº 15/2024, art. 9º, § 3º",
         "Divulgação em sítio eletrônico, aplicativos, mídias sociais e canais de atendimento, por no mínimo três meses.", 3,
         [("Divulgação pública por, no mínimo, três meses", True), ("Não comunicar", False),
          ("Comunicar só a ANPD", False), ("Anúncio de um dia no jornal", False)]),
        ("Vazamento de logins e senhas (dados de autenticação) é critério de 'risco ou dano relevante'?",
         "Res. CD/ANPD nº 15/2024, art. 5º, IV",
         "Sim: dados de autenticação em sistemas são um dos critérios (art. 5º, IV), ao lado de sensíveis, de "
         "crianças/adolescentes/idosos, financeiros, sob sigilo e em larga escala.", 2,
         [("Sim, é critério expresso da Resolução", True), ("Não, senha não é dado pessoal", False),
          ("Só se forem senhas de administrador", False), ("Só se houver mais de mil", False)]),
        ("Como a ANPD define 'larga escala' para fins de incidente?", "Res. CD/ANPD nº 15/2024, art. 5º, § 2º",
         "Número significativo de titulares, considerando ainda o volume de dados, a duração, a frequência e a "
         "extensão geográfica da localização dos titulares.", 3,
         [("Número significativo de titulares, considerando volume, duração, frequência e extensão geográfica", True),
          ("Mais de 1 milhão de registros, fixo", False), ("Qualquer banco de dados", False),
          ("Só bancos de dados públicos", False)]),
        ("A obrigação de garantir a segurança da informação vale mesmo após o término do tratamento?", "Art. 47",
         "Sim: os agentes e qualquer pessoa que intervenha no tratamento obrigam-se a garantir a segurança mesmo após "
         "o seu término (Art. 47).", 2,
         [("Sim, mesmo após o término", True), ("Não, só durante", False), ("Só para dados sensíveis", False),
          ("Só se houver contrato", False)]),
        ("Os sistemas usados para tratar dados pessoais devem ser estruturados para:", "Art. 49",
         "Atender aos requisitos de segurança, aos padrões de boas práticas e de governança e aos princípios gerais da "
         "lei (Art. 49).", 2,
         [("Atender a requisitos de segurança, boas práticas e princípios da lei", True),
          ("Maximizar a coleta de dados", False), ("Evitar logs", False), ("Ignorar a governança", False)]),
        ("'Privacidade por padrão', pelo Guia do Encarregado da ANPD, significa que as configurações protetivas:",
         "Guia Atuação do Encarregado (ANPD, 2024); Art. 46, § 2º",
         "São acionadas automaticamente por padrão, sem intervenção do usuário; e as medidas de segurança devem "
         "existir desde a concepção do produto (Art. 46, § 2º).", 2,
         [("Vêm ativadas automaticamente, sem ação do usuário", True), ("Devem ser ativadas pelo usuário", False),
          ("São opcionais", False), ("Só existem em produtos pagos", False)]),
        ("Uso de celulares pessoais para fins institucionais, segundo o Guia de Segurança da ANPD:", "Guia Segurança (ANPD, 2021)",
         "Não é recomendado sem medidas equivalentes às dos dispositivos institucionais; recomenda-se MFA, separação "
         "de dados e possibilidade de apagamento remoto.", 2,
         [("Não recomendado sem medidas equivalentes (MFA, apagamento remoto)", True), ("Livremente permitido", False),
          ("Obrigatório", False), ("Proibido pela lei", False)]),
        ("Ao contratar serviço de nuvem, o Guia da ANPD recomenda:", "Guia Segurança (ANPD, 2021)",
         "Contrato com acordo de nível de serviço (SLA) contemplando a segurança dos dados armazenados e MFA para o "
         "acesso.", 2,
         [("SLA que contemple a segurança dos dados e MFA no acesso", True), ("Só o menor preço", False),
          ("Sem contrato", False), ("Senha compartilhada pela equipe", False)]),
        ("Ao usar as cláusulas-padrão da ANPD para transferir dados a um provedor no exterior, a empresa deve:",
         "Res. CD/ANPD nº 19/2024, art. 16",
         "Adotá-las integralmente e sem alteração do texto do Anexo II; outras cláusulas do contrato não podem "
         "excluir, modificar ou contrariar as cláusulas-padrão.", 3,
         [("Adotá-las integralmente, sem alterar o texto", True), ("Adaptá-las livremente", False),
          ("Traduzi-las para o inglês apenas", False), ("Substituí-las pelo contrato do fornecedor", False)]),
        ("Servidores na União Europeia: a transferência conta com qual mecanismo do Art. 33?", "Art. 33, I; Res. CD/ANPD nº 32/2026",
         "Decisão de adequação: a ANPD reconheceu a União Europeia e o EEE (Islândia, Liechtenstein e Noruega) como "
         "adequados (Res. nº 32/2026), com reavaliação em quatro anos.", 3,
         [("Decisão de adequação da ANPD (Res. 32/2026)", True), ("Nenhum; é proibido", False),
          ("Autorização do titular apenas", False), ("Cláusulas do fornecedor", False)]),
        ("Um site no exterior que coleta dados diretamente de usuários no Brasil realiza 'transferência internacional'?",
         "Res. CD/ANPD nº 19/2024, arts. 6º e 8º",
         "Não: a coleta internacional de dados não caracteriza transferência internacional (art. 6º) — mas a LGPD se "
         "aplica ao tratamento (Art. 3º).", 3,
         [("Não, é coleta internacional; a LGPD ainda se aplica", True), ("Sim, sempre", False),
          ("Sim, e exige cláusulas-padrão", False), ("Não, e a LGPD não se aplica", False)]),
        ("Eliminação de dados em mídias físicas descartadas, segundo a ANPD:", "Guia Segurança (ANPD, 2021)",
         "Formatação ou destruição física; se o descarte for por terceiros, contrato com cláusulas de registro da "
         "destruição.", 2,
         [("Formatação/destruição física; terceiros com registro da destruição", True), ("Jogar no lixo comum", False),
          ("Doar com os dados", False), ("Guardar para sempre", False)]),
        ("Compartilhar logins e senhas entre colegas é, para o Guia de Segurança da ANPD:", "Guia Segurança (ANPD, 2021)",
         "Prática a evitar: não compartilhar contas nem credenciais, para preservar autenticação, autorização e "
         "auditoria.", 1,
         [("Prática a evitar", True), ("Recomendado para agilidade", False), ("Obrigatório em férias", False),
          ("Indiferente", False)]),
        ("A ANPD determinou 'ampla divulgação' de um incidente em meios de comunicação. Isso é a sanção de 'publicização'?",
         "Res. CD/ANPD nº 15/2024, art. 19, § 6º, e art. 22",
         "Não: a ampla divulgação é providência para salvaguardar titulares e não se confunde com a sanção de "
         "publicização da infração; as providências do art. 19 não constituem sanções.", 3,
         [("Não: é providência de salvaguarda, não sanção", True), ("Sim, é a mesma coisa", False),
          ("Sim, e cumulativa com multa", False), ("É uma multa diária", False)]),
    ],

    # ───────────────────────────── ATENDIMENTO e SAC ─────────────────────────────
    "ATENDIMENTO": [
        ("Alguém liga pedindo 'todos os dados' de um cliente. Antes de responder, o atendimento deve considerar que:",
         "Art. 18, § 3º; Art. 46",
         "Os direitos são exercidos por requerimento expresso do titular ou de representante legalmente constituído "
         "(Art. 18, § 3º), e a empresa deve proteger os dados de acesso não autorizado (Art. 46) — logo, confirma-se "
         "quem está pedindo.", 2,
         [("Só o titular ou representante legal pode pedir; confirmar a identidade", True),
          ("Deve entregar imediatamente a qualquer pessoa", False),
          ("Deve negar sempre", False), ("Deve cobrar uma taxa", False)]),
        ("A consulta do titular sobre a forma e a duração do tratamento e sobre a integralidade dos seus dados deve ser:",
         "Art. 6º, IV; Art. 18, § 5º",
         "Facilitada e gratuita (princípio do livre acesso, Art. 6º, IV); os requerimentos são atendidos sem custos "
         "(Art. 18, § 5º).", 1,
         [("Facilitada e gratuita", True), ("Paga e burocrática", False), ("Negada", False),
          ("Somente presencial", False)]),
        ("Registrar cada pedido do titular, com data e resposta, atende ao princípio da:", "Art. 6º, X",
         "Responsabilização e prestação de contas: demonstrar a adoção de medidas eficazes e comprovar o cumprimento "
         "das normas (Art. 6º, X).", 1,
         [("Responsabilização e prestação de contas", True), ("Publicidade", False), ("Gratuidade", False),
          ("Reciprocidade", False)]),
        ("Um parente pede os dados de outra pessoa, 'porque mora na mesma casa'. O atendimento deve:", "Art. 18, § 3º",
         "Não entregar: o requerimento é do titular ou de representante legalmente constituído (Art. 18, § 3º).", 2,
         [("Recusar: só o titular ou representante legal pode requerer", True), ("Entregar por gentileza", False),
          ("Entregar após pagamento", False), ("Enviar por e-mail ao parente", False)]),
        ("O cliente pergunta se a empresa trata dados dele. Esse é o direito de:", "Art. 18, I",
         "Confirmação da existência de tratamento (Art. 18, I) — em formato simplificado, imediatamente (Art. 19, I).", 1,
         [("Confirmação da existência de tratamento", True), ("Portabilidade", False), ("Anonimização", False),
          ("Revogação", False)]),
        ("Prazos do Art. 19 para confirmação de existência de tratamento e acesso aos dados:", "Art. 19, I e II",
         "Formato simplificado: imediatamente; declaração clara e completa (origem, critérios, finalidade): até 15 dias "
         "do requerimento.", 2,
         [("Simplificado: imediato; declaração completa: até 15 dias", True), ("30 dias em qualquer caso", False),
          ("72 horas", False), ("Não há prazo", False)]),
        ("O cliente informa que seu endereço no cadastro está errado. Ele exerce o direito de:", "Art. 18, III",
         "Correção de dados incompletos, inexatos ou desatualizados (Art. 18, III).", 1,
         [("Correção", True), ("Portabilidade", False), ("Bloqueio", False), ("Revogação", False)]),
        ("O cliente pede a eliminação dos dados que forneceu com consentimento. A empresa:", "Art. 18, VI; Art. 16",
         "Deve eliminar (Art. 18, VI), exceto nas hipóteses de conservação do Art. 16 — por exemplo, obrigação legal.", 2,
         [("Elimina, salvo hipótese legal de conservação (Art. 16)", True), ("Recusa sempre", False),
          ("Cobra uma taxa", False), ("Só elimina após 5 anos", False)]),
        ("Dados desnecessários, excessivos ou tratados em desconformidade com a lei dão ao titular o direito de pedir:",
         "Art. 18, IV",
         "Anonimização, bloqueio ou eliminação desses dados (Art. 18, IV).", 2,
         [("Anonimização, bloqueio ou eliminação", True), ("Indenização automática", False),
          ("Cópia impressa apenas", False), ("Nada", False)]),
        ("Ao pedir consentimento, o atendimento deve informar ao titular:", "Art. 18, VIII",
         "A possibilidade de não fornecer o consentimento e as consequências da negativa (Art. 18, VIII).", 2,
         [("Que pode recusar e quais as consequências", True), ("Que é obrigatório consentir", False),
          ("Que a recusa cancela a conta", False), ("Nada além do pedido", False)]),
        ("A empresa recebe um pedido, mas não é ela quem trata os dados daquela pessoa. Ela deve:", "Art. 18, § 4º, I",
         "Comunicar que não é agente de tratamento dos dados e indicar, sempre que possível, o agente (Art. 18, § 4º, I).", 3,
         [("Responder que não é agente de tratamento e indicar quem é, se possível", True), ("Ignorar", False),
          ("Inventar uma resposta", False), ("Encaminhar à polícia", False)]),
        ("As informações e dados pedidos pelo titular podem ser fornecidos:", "Art. 19, § 2º",
         "A critério do titular: por meio eletrônico seguro e idôneo, ou sob forma impressa (Art. 19, § 2º).", 2,
         [("Por meio eletrônico seguro ou impresso, a critério do titular", True), ("Só por carta", False),
          ("Só presencialmente", False), ("Só por telefone", False)]),
        ("Se a empresa não resolver a reclamação, o titular pode peticionar:", "Art. 18, §§ 1º e 8º; Art. 55-J, V",
         "Perante a ANPD (que aprecia petições após reclamação ao controlador não solucionada no prazo regulamentar) "
         "e também perante os organismos de defesa do consumidor.", 3,
         [("À ANPD e aos organismos de defesa do consumidor", True), ("Só ao Judiciário", False),
          ("A ninguém", False), ("Só à polícia", False)]),
        ("Gravar as ligações do SAC exige, em primeiro lugar:", "Art. 6º, I e VI; Art. 9º",
         "Transparência e finalidade informada: o titular tem direito a informações claras sobre o tratamento, sua "
         "finalidade e duração (Art. 9º; Art. 6º, I e VI).", 2,
         [("Informar o titular sobre a gravação e sua finalidade", True), ("Nada, gravação é livre", False),
          ("Autorização da ANPD", False), ("Consentimento por escrito de todos os atendentes", False)]),
        ("Um atendente 'dá uma olhada' no cadastro de um conhecido, sem necessidade para o atendimento. Isso é:",
         "Art. 6º, III; Art. 46; Guia Segurança (ANPD)",
         "Acesso sem finalidade e fora da necessidade, contrário ao controle de acesso por menor privilégio — e "
         "potencial incidente (acesso não autorizado, Art. 46).", 2,
         [("Acesso indevido: fere necessidade e controle de acesso", True), ("Normal, ele tem senha", False),
          ("Permitido se não contar a ninguém", False), ("Boa prática de atendimento", False)]),
        ("Durante o atendimento o cliente relata uma doença. Essa informação é:", "Art. 5º, II; Art. 11",
         "Dado pessoal sensível (saúde), sujeito às hipóteses restritas do Art. 11 — registrar só se indispensável e "
         "com base legal adequada.", 2,
         [("Dado sensível, sujeito ao Art. 11", True), ("Dado comum", False), ("Dado público", False),
          ("Dado irrelevante", False)]),
        ("Consentimento colhido por telefone é válido?", "Art. 8º, caput e § 2º",
         "Sim, se fornecido por meio que demonstre a manifestação de vontade do titular (Art. 8º, caput); o ônus de "
         "provar que foi obtido conforme a lei é do controlador (§ 2º) — daí registrar.", 2,
         [("Sim, se demonstrar a vontade; o controlador deve conseguir provar", True),
          ("Não, só por escrito", False), ("Sim, sem necessidade de registro", False), ("Não, nunca", False)]),
        ("O cliente quer 'cancelar a autorização' que deu para receber ofertas. Isso é:", "Art. 8º, § 5º; Art. 18, IX",
         "Revogação do consentimento, a qualquer momento, por procedimento gratuito e facilitado.", 1,
         [("Revogação do consentimento, gratuita e facilitada", True), ("Impossível", False),
          ("Pedido de portabilidade", False), ("Motivo para encerrar a conta", False)]),
        ("O cliente pede para 'levar' seus dados para um concorrente. Esse direito:", "Art. 18, V",
         "É a portabilidade a outro fornecedor, mediante requisição expressa, conforme regulamentação da ANPD e "
         "observados os segredos comercial e industrial (Art. 18, V).", 2,
         [("É a portabilidade, mediante requisição expressa", True), ("Não existe", False),
          ("Só vale para bancos", False), ("Exige ordem judicial", False)]),
        ("Quando o tratamento tem origem em consentimento ou contrato, o titular pode solicitar:", "Art. 19, § 3º",
         "Cópia eletrônica integral dos seus dados, em formato que permita a utilização subsequente, observados os "
         "segredos comercial e industrial (Art. 19, § 3º).", 3,
         [("Cópia eletrônica integral em formato reutilizável", True), ("Apenas um resumo verbal", False),
          ("Nada além da confirmação", False), ("Só cópia impressa", False)]),
        ("Após corrigir ou eliminar dados a pedido do titular, o controlador deve:", "Art. 18, § 6º",
         "Informar de maneira imediata aos agentes com quem realizou uso compartilhado, para que repitam o "
         "procedimento — salvo se impossível ou desproporcional (Art. 18, § 6º).", 3,
         [("Avisar os agentes com quem compartilhou, para repetirem o procedimento", True),
          ("Nada mais", False), ("Avisar a ANPD", False), ("Cobrar do titular", False)]),
        ("Os direitos do titular podem ser exercidos:", "Art. 18, caput",
         "A qualquer momento e mediante requisição ao controlador (Art. 18, caput).", 1,
         [("A qualquer momento, mediante requisição", True), ("Só uma vez por ano", False),
          ("Só no primeiro mês do contrato", False), ("Só após reclamação no Procon", False)]),
        ("Mesmo um agente de pequeno porte dispensado de indicar encarregado deve:", "Res. CD/ANPD nº 2/2022, art. 11, § 1º",
         "Disponibilizar um canal de comunicação com o titular de dados, para aceitar reclamações e comunicações "
         "(Art. 41, § 2º, I).", 2,
         [("Manter um canal de comunicação com o titular", True), ("Nada", False),
          ("Encaminhar tudo à ANPD", False), ("Contratar um advogado", False)]),
        ("A comunicação de incidente aos titulares deve informar, entre outros:", "Res. CD/ANPD nº 15/2024, art. 9º",
         "A natureza dos dados, os riscos, as medidas, a data do conhecimento e o contato para obter informações "
         "(inclusive do encarregado, quando aplicável).", 3,
         [("Dados afetados, riscos, medidas e um contato para informações", True), ("Só um pedido de desculpas", False),
          ("A lista dos outros afetados", False), ("O valor da multa", False)]),
        ("A linguagem da comunicação de incidente ao titular deve ser:", "Res. CD/ANPD nº 15/2024, art. 9º, § 1º",
         "Simples e de fácil entendimento, de forma direta e individualizada quando for possível identificá-los.", 2,
         [("Simples, direta e individualizada quando possível", True), ("Técnica e jurídica", False),
          ("Genérica, em nota de rodapé", False), ("Só em inglês", False)]),
        ("Um agente de pequeno porte pode fornecer a confirmação/acesso em formato simplificado em até:",
         "Res. CD/ANPD nº 2/2022, art. 15",
         "Quinze dias, contados do requerimento — flexibilização do 'imediatamente' do Art. 19, I.", 3,
         [("15 dias", True), ("Imediatamente, sem exceção", False), ("90 dias", False), ("Nunca", False)]),
        ("Coletar dados de uma criança apenas para contatar os pais é permitido sem consentimento parental se:", "Art. 14, § 3º",
         "Os dados forem usados uma única vez, sem armazenamento, e não repassados a terceiros (Art. 14, § 3º).", 3,
         [("Usados uma única vez, sem armazenar nem repassar", True), ("Guardados por 5 anos", False),
          ("Compartilhados com parceiros", False), ("Nunca é permitido", False)]),
        ("O titular reclama de um tratamento feito com base em obrigação legal. Ele pode se opor?", "Art. 18, § 2º",
         "Pode opor-se a tratamento realizado com fundamento em hipótese de dispensa de consentimento em caso de "
         "descumprimento da lei (Art. 18, § 2º).", 3,
         [("Sim, se houver descumprimento da lei", True), ("Nunca", False), ("Sempre, sem motivo", False),
          ("Só com advogado", False)]),
        ("Um cliente que exerceu seus direitos passa a ser mal atendido por 'dar trabalho'. A LGPD:", "Art. 21; Art. 6º, IX",
         "Proíbe: os dados referentes ao exercício regular de direitos pelo titular não podem ser utilizados em seu "
         "prejuízo (Art. 21), e o tratamento não pode ser discriminatório (Art. 6º, IX).", 2,
         [("Proíbe usar o exercício de direitos em prejuízo do titular", True), ("Permite", False),
          ("Não trata do tema", False), ("Recomenda", False)]),
        ("Entre as informações que devem estar acessíveis ao titular está o contato do controlador. Onde isso consta?",
         "Art. 9º, III e IV",
         "Art. 9º: identificação do controlador (III) e informações de contato (IV), de forma clara, adequada e ostensiva.", 1,
         [("Art. 9º — identificação e contato do controlador", True), ("Art. 52 — sanções", False),
          ("Art. 33 — transferência internacional", False), ("Não consta da lei", False)]),
        ("Tratar dados para fins discriminatórios ilícitos ou abusivos viola o princípio da:", "Art. 6º, IX",
         "Não discriminação: impossibilidade de realização do tratamento para fins discriminatórios ilícitos ou "
         "abusivos (Art. 6º, IX).", 1,
         [("Não discriminação", True), ("Livre acesso", False), ("Segurança", False), ("Qualidade dos dados", False)]),
    ],

    # ───────────────────────────── JURÍDICO e Compras ─────────────────────────────
    "JURIDICO": [
        ("O operador deve realizar o tratamento:", "Art. 39",
         "Segundo as instruções fornecidas pelo controlador, que verificará a observância das próprias instruções e "
         "das normas (Art. 39). O Guia da ANPD recomenda formalizar isso em contrato.", 1,
         [("Segundo as instruções do controlador, que as verifica", True), ("Como julgar melhor", False),
          ("Conforme a ANPD determinar caso a caso", False), ("Sem qualquer instrução", False)]),
        ("Ao contratar um fornecedor que tratará dados (operador), em que hipótese ele responde solidariamente com a empresa?",
         "Art. 42, § 1º, I",
         "Quando descumpre as obrigações da legislação ou não segue as instruções lícitas do controlador — equiparando-se "
         "ao controlador, salvo excludentes do Art. 43. É a única hipótese de equiparação (Guia de Agentes da ANPD).", 2,
         [("Descumpre a lei ou as instruções lícitas do controlador", True), ("Sempre", False), ("Nunca", False),
          ("Só se for empresa pública", False)]),
        ("Dois controladores diretamente envolvidos no tratamento que causou dano:", "Art. 42, § 1º, II",
         "Respondem solidariamente, salvo nos casos de exclusão do Art. 43 (Art. 42, § 1º, II).", 3,
         [("Respondem solidariamente", True), ("Só o maior responde", False), ("Nenhum responde", False),
          ("Só o que faturou mais", False)]),
        ("Os agentes de tratamento NÃO serão responsabilizados quando provarem que:", "Art. 43",
         "Não realizaram o tratamento que lhes é atribuído; ou o realizaram sem violar a legislação; ou o dano decorre "
         "de culpa exclusiva do titular ou de terceiro (Art. 43).", 3,
         [("Não trataram, trataram sem violar a lei, ou houve culpa exclusiva do titular/terceiro", True),
          ("Têm seguro", False), ("Pediram desculpas", False), ("São pequenas empresas", False)]),
        ("No processo civil, o juiz pode inverter o ônus da prova a favor do titular quando:", "Art. 42, § 2º",
         "A alegação for verossímil, houver hipossuficiência para produzir prova, ou a prova for excessivamente onerosa "
         "ao titular (Art. 42, § 2º).", 3,
         [("Alegação verossímil, hipossuficiência ou prova excessivamente onerosa", True), ("Sempre", False),
          ("Nunca", False), ("Só em ações coletivas", False)]),
        ("Quem repara o dano ao titular tem direito de regresso contra os demais responsáveis?", "Art. 42, § 4º",
         "Sim, na medida de sua participação no evento danoso (Art. 42, § 4º).", 3,
         [("Sim, na medida da participação de cada um", True), ("Não", False), ("Só contra o operador", False),
          ("Só contra a ANPD", False)]),
        ("O tratamento é considerado irregular quando:", "Art. 44",
         "Deixa de observar a legislação ou não fornece a segurança que o titular pode esperar, consideradas as "
         "circunstâncias (modo, resultado e riscos esperados, técnicas disponíveis à época).", 2,
         [("Descumpre a lei ou não dá a segurança que o titular pode esperar", True),
          ("Apenas quando há multa", False), ("Só se houver vazamento", False), ("Só em contratos", False)]),
        ("Entre as garantias do Art. 33, II, para transferência internacional estão:", "Art. 33, II",
         "Cláusulas contratuais específicas, cláusulas-padrão contratuais, normas corporativas globais e selos, "
         "certificados e códigos de conduta regularmente emitidos.", 2,
         [("Cláusulas específicas, cláusulas-padrão, normas corporativas globais, selos e códigos", True),
          ("Apenas o consentimento", False), ("Só autorização judicial", False), ("Nenhuma; é proibida", False)]),
        ("Pela Resolução CD/ANPD nº 19/2024, toda transferência internacional exige, cumulativamente:",
         "Res. CD/ANPD nº 19/2024, art. 9º",
         "Uma hipótese legal do Art. 7º ou 11 E um mecanismo válido (adequação, cláusulas-padrão, normas corporativas "
         "globais, cláusulas específicas ou as demais hipóteses do Art. 33), limitada ao mínimo necessário.", 3,
         [("Base legal E um mecanismo válido do Art. 33", True), ("Só a base legal", False),
          ("Só o mecanismo", False), ("Nada, se for para a matriz", False)]),
        ("As cláusulas-padrão contratuais da ANPD são válidas quando:", "Res. CD/ANPD nº 19/2024, art. 16",
         "Adotadas integralmente e sem alteração do texto do Anexo II; cláusulas adicionais não podem excluir, "
         "modificar ou contrariar as padrão.", 3,
         [("Adotadas integralmente, sem alteração do texto", True), ("Adaptadas ao negócio", False),
          ("Resumidas em uma página", False), ("Substituídas por NDA", False)]),
        ("Cláusulas contratuais ESPECÍFICAS para transferência internacional:", "Res. CD/ANPD nº 19/2024, art. 21, § 1º",
         "Só são aprovadas quando a transferência não puder ser feita pelas cláusulas-padrão, por circunstâncias "
         "excepcionais comprovadas, e exigem aprovação prévia da ANPD.", 3,
         [("São excepcionais e dependem de aprovação prévia da ANPD", True), ("São a regra geral", False),
          ("Dispensam a ANPD", False), ("Valem sem base legal", False)]),
        ("Normas corporativas globais destinam-se a transferências:", "Res. CD/ANPD nº 19/2024, arts. 25 a 28",
         "Entre organizações do mesmo grupo ou conglomerado, com caráter vinculante, vinculadas a programa de "
         "governança e sujeitas a aprovação prévia da ANPD.", 3,
         [("Dentro do mesmo grupo econômico, com aprovação prévia da ANPD", True), ("A qualquer terceiro", False),
          ("Só ao Poder Público", False), ("Só a países adequados", False)]),
        ("Qual organismo internacional foi reconhecido como adequado pela ANPD?", "Res. CD/ANPD nº 32/2026; Art. 33, I",
         "A União Europeia (e o EEE: Islândia, Liechtenstein e Noruega), pela Resolução nº 32/2026, exceto para "
         "segurança pública, defesa e persecução penal; reavaliação em quatro anos.", 1,
         [("A União Europeia e o Espaço Econômico Europeu", True), ("Os Estados Unidos", False),
          ("O Mercosul", False), ("Nenhum até hoje", False)]),
        ("Prazo dado pela Resolução nº 19/2024 para incorporar as cláusulas-padrão aos contratos existentes:",
         "Res. CD/ANPD nº 19/2024, art. 2º, parágrafo único",
         "Até 12 meses contados da publicação da Resolução (23/08/2024).", 3,
         [("12 meses", True), ("30 dias", False), ("5 anos", False), ("Não há prazo", False)]),
        ("A indicação do encarregado deve ser feita:", "Res. CD/ANPD nº 18/2024, art. 3º",
         "Por ato formal do agente de tratamento — documento escrito, datado e assinado — com as formas de atuação e "
         "atividades, apresentado à ANPD quando solicitado. Não precisa ser comunicado à ANPD.", 1,
         [("Por ato formal escrito, datado e assinado", True), ("Verbalmente", False),
          ("Por registro obrigatório na ANPD", False), ("Por e-mail ao Procon", False)]),
        ("Nas ausências e impedimentos do encarregado:", "Res. CD/ANPD nº 18/2024, art. 4º",
         "A função será exercida por substituto formalmente designado.", 2,
         [("Atua um substituto formalmente designado", True), ("A função fica vaga", False),
          ("A ANPD indica alguém", False), ("Qualquer gerente assume", False)]),
        ("A indicação de encarregado pelo OPERADOR é:", "Res. CD/ANPD nº 18/2024, art. 6º",
         "Facultativa, considerada política de boas práticas de governança (Art. 52, § 1º, IX).", 3,
         [("Facultativa, como boa prática", True), ("Obrigatória com multa", False), ("Proibida", False),
          ("Obrigatória só para nuvem", False)]),
        ("Perante a ANPD, o responsável pela conformidade do tratamento é:", "Res. CD/ANPD nº 18/2024, arts. 11 e 17",
         "O agente de tratamento — o desempenho das atribuições não confere ao encarregado a responsabilidade pela "
         "conformidade (art. 17).", 3,
         [("O agente de tratamento, não o encarregado", True), ("O encarregado, pessoalmente", False),
          ("O advogado da empresa", False), ("O titular", False)]),
        ("Divulgar no site apenas um e-mail 'encarregado@empresa.com.br', sem nome, atende à lei?",
         "Res. CD/ANPD nº 18/2024, art. 9º; Guia Atuação do Encarregado (ANPD, 2024)",
         "Não: é informação de contato, mas não identifica o encarregado — exige-se o nome completo (pessoa natural) "
         "ou o nome empresarial mais o nome da pessoa natural responsável (pessoa jurídica).", 2,
         [("Não: falta a identificação (nome completo)", True), ("Sim, basta o e-mail", False),
          ("Sim, se houver telefone", False), ("Não é preciso divulgar nada", False)]),
        ("Há controladoria conjunta, pelo Guia da ANPD, quando:", "Guia Orientativo Agentes de Tratamento (ANPD, v2.0, 2022)",
         "Dois ou mais controladores determinam em conjunto, de forma comum ou convergente, as finalidades e os "
         "elementos essenciais do tratamento, por acordo que estabeleça as responsabilidades.", 3,
         [("Controladores decidem juntos finalidades e elementos essenciais, com acordo de responsabilidades", True),
          ("Duas empresas usam o mesmo software", False), ("Há um operador comum", False),
          ("Os dados são os mesmos, com objetivos distintos", False)]),
        ("O elemento que distingue controlador de operador é:", "Guia Orientativo Agentes de Tratamento (ANPD, v2.0, 2022)",
         "O poder de decisão: o operador só pode agir no limite das finalidades determinadas pelo controlador; a "
         "finalidade é sempre estabelecida pelo controlador.", 2,
         [("O poder de decisão sobre finalidades e elementos essenciais", True), ("O tamanho da empresa", False),
          ("Quem tem mais funcionários", False), ("Quem assinou o contrato primeiro", False)]),
        ("Contrato com terceirizado exige 'ciência ao controlador' quando o operador:", "Guia Orientativo Agentes de Tratamento (ANPD, v2.0, 2022)",
         "Contrata um suboperador — o Guia lista entre as obrigações do operador dar ciência ao controlador em caso de "
         "contrato com suboperador, e recomenda autorização formal.", 3,
         [("Contrata um suboperador", True), ("Muda de endereço", False), ("Troca de contador", False),
          ("Faz backup", False)]),
        ("A ANPD pode exigir o RIPD do controlador quando:", "Art. 38; Art. 10, § 3º",
         "A qualquer tempo, nos termos de regulamento — inclusive quando o tratamento se fundar no legítimo interesse "
         "(Art. 10, § 3º). O relatório descreve dados, metodologia, segurança e mitigação de riscos.", 2,
         [("Determinar, inclusive em tratamentos por legítimo interesse", True), ("Nunca", False),
          ("Só após multa", False), ("Só para órgãos públicos", False)]),
        ("As sanções de suspensão do banco de dados, suspensão da atividade e proibição só podem ser aplicadas:",
         "Art. 52, § 6º, I",
         "Após já ter sido imposta ao menos uma das sanções de multa simples, multa diária, publicização, bloqueio ou "
         "eliminação, para o mesmo caso concreto.", 3,
         [("Depois de outra sanção no mesmo caso concreto", True), ("Como primeira sanção", False),
          ("Só por decisão judicial", False), ("Nunca", False)]),
        ("Pela dosimetria da ANPD, 'reincidência específica' é repetir infração ao mesmo dispositivo no período de:",
         "Res. CD/ANPD nº 4/2023, art. 2º",
         "Cinco anos, contados do trânsito em julgado do processo administrativo sancionador; a genérica é qualquer "
         "infração no mesmo período.", 3,
         [("5 anos", True), ("1 ano", False), ("10 anos", False), ("Sem limite de tempo", False)]),
        ("Tratar dados 'sem amparo em uma das hipóteses legais' torna a infração, pela Resolução nº 4/2023:",
         "Res. CD/ANPD nº 4/2023, art. 8º",
         "Grave — quando, além de poder afetar significativamente direitos, ocorre sem hipótese legal, com dados "
         "sensíveis ou de crianças, em larga escala, com vantagem econômica, entre outras.", 3,
         [("Grave", True), ("Leve", False), ("Irrelevante", False), ("Isenta de sanção", False)]),
        ("A advertência é a sanção cabível quando:", "Res. CD/ANPD nº 4/2023, art. 9º",
         "A infração for leve ou média e não caracterizar reincidência específica, ou quando houver necessidade de "
         "medidas corretivas.", 2,
         [("Infração leve ou média sem reincidência específica", True), ("Sempre, na primeira vez", False),
          ("Só para pequenas empresas", False), ("Nunca", False)]),
        ("Um programa de governança em privacidade (Art. 50, § 2º) deve, entre outros pontos:", "Art. 50, § 2º, I",
         "Contar com planos de resposta a incidentes e remediação, políticas baseadas em avaliação de riscos, "
         "mecanismos de supervisão e atualização constante.", 2,
         [("Contar com plano de resposta a incidentes e avaliação de riscos", True), ("Ser apenas um documento assinado", False),
          ("Substituir o encarregado", False), ("Dispensar o ROPA", False)]),
        ("Vazamentos individuais ou acessos não autorizados podem ser objeto de:", "Art. 52, § 7º",
         "Conciliação direta entre controlador e titular; sem acordo, o controlador fica sujeito às penalidades do Art. 52.", 3,
         [("Conciliação direta entre controlador e titular", True), ("Apenas processo criminal", False),
          ("Nada", False), ("Só multa automática", False)]),
        ("Dados pessoais de acesso público (ex.: diário oficial) podem ser tratados considerando:", "Art. 7º, § 3º",
         "A finalidade, a boa-fé e o interesse público que justificaram sua disponibilização (Art. 7º, § 3º).", 3,
         [("Finalidade, boa-fé e interesse público da disponibilização", True), ("Nada, são livres", False),
          ("Só com consentimento", False), ("Só pelo Poder Público", False)]),
        ("Violações de direitos do titular em relações de consumo:", "Art. 45",
         "Permanecem sujeitas às regras de responsabilidade da legislação pertinente (CDC), além da LGPD (Art. 45).", 2,
         [("Seguem também as regras do direito do consumidor", True), ("Ficam isentas", False),
          ("Só a LGPD se aplica", False), ("Só o CDC se aplica", False)]),
        ("A aplicação das sanções da LGPD compete:", "Art. 55-K",
         "Exclusivamente à ANPD, cujas competências prevalecem, quanto à proteção de dados, sobre as de outros órgãos.", 1,
         [("Exclusivamente à ANPD", True), ("A qualquer órgão de fiscalização", False), ("Ao Procon", False),
          ("Ao Banco Central", False)]),
        ("Os regulamentos e normas da ANPD devem ser precedidos de:", "Art. 55-J, § 2º",
         "Consulta e audiência públicas e análises de impacto regulatório (Art. 55-J, § 2º).", 2,
         [("Consulta e audiência públicas e análise de impacto regulatório", True), ("Nada", False),
          ("Aprovação do Senado em cada caso", False), ("Referendo", False)]),
    ],
}
